"use client";

import React, { createContext, useContext, useState } from "react";

export type Language = "EN" | "NE" | "HI" | "BN";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
};

const translations: Record<Language, Record<string, string>> = {
    EN: {
        "nav.home": "Home",
        "nav.why": "Story",
        "nav.change": "Change",
        "nav.economy": "Opportunity",
        "nav.services": "Services",
        "nav.challenges": "Challenges",
        "nav.voices": "Voices",
        "nav.village": "Talent",
        "nav.hub": "Hub",
        "nav.partners": "Partners",
        "nav.updates": "Updates",
        "hero.location": "Lamahatta · Darjeeling",
        "hero.title": "Seemana Gaon",
        "hero.subtitle": "A village economy in transition",
        "hero.houses": "Houses",
        "hero.residents": "Residents",
        "hero.potential": "Potential",
        "hero.scroll": "Scroll to explore ↓",
        "hero.opportunity": "See the Opportunity",
        "hero.story": "Our Story",
        "hero.join": "Join the Village",
        "hero.panorama.title": "A Wide Horizon",
        "hero.panorama.desc": "Every corner of Seemana Gaon is connected by a shared history and breathtaking views of the surrounding mountains.",
        "hero.main_title": "Sunaray Gaon is not just a village website.",
        "hero.main_subtitle": "It is the front door to a living village economy.",
        "opportunities.empty": "No opportunities listed yet.",
        "opportunities.add": "Add Opportunity",
        "opportunities.desc": "List jobs, training, contracts, and business needs.",
        "voices.label": "Voices page",
        "voices.title": "This page should become the village opinion board.",
        "voices.subtitle": "People should be able to say what is needed, what is working, and what should be built next.",
        "voices.post_heading": "What should be posted here",
        "voices.desc": "This page should not be decorative. It should become the place where the village speaks in categories that help action happen.",
        "voices.topic": "Topic",
        "voices.quote": "If the village cannot state its needs clearly, other people will define them badly.",
        "voices.cta.updates": "Go to community updates",
        "voices.cta.hub": "Enter the hub",
        "opportunities.villagers": "For Villagers",
        "opportunities.villagers.desc": "Access services, schemes & opportunities",
        "opportunities.investors": "For Investors",
        "opportunities.investors.desc": "See the opportunity gaps",
        "opportunities.partners": "For Partners",
        "opportunities.partners.desc": "Collaborate with us",
        "opportunities.enter": "Enter →",
        "location.label": "Location",
        "location.title": "Where We Are",
        "location.subtitle": "Between 6th Mile and Takdah. A hidden gem in the hills.",
        "location.satellite": "Satellite View",
        "location.houses": "22 Houses nestled in the forest",
        "location.maps": "Open in Google Maps ↗",
        "life.quote": "Good food. Honest hospitality. Humor and warmth. A sense of belonging.",
        "life.attribution": "— What visitors experience here",
        "gaps.label": "For Investors",
        "gaps.title": "Opportunity Gaps",
        "gaps.subtitle": "High demand. Zero supply. Ideal for investment.",
        "gaps.homestay": "Homestay",
        "gaps.cafe": "Cafe",
        "gaps.guide": "Guide",
        "gaps.organic": "Organic Farm",
        "gaps.status": "Gap",
        "gaps.potential": "Homestay Potential: Mountain views, authentic experience",
        "economy.label": "Active Economy",
        "economy.title": "What We Do",
        "economy.subtitle": "From cooking to coding. A working village economy.",
        "economy.view": "View All Services",
        "economy.food": "Food & Hospitality",
        "economy.agriculture": "Agriculture",
        "economy.construction": "Construction",
        "economy.digital": "Digital Services",
        "economy.active": "active",
        "vision.label": "The Vision",
        "vision.title": "What We're Building",
        "vision.portal": "Village Portal",
        "vision.portal.desc": "One platform for all services",
        "vision.hub": "Tourism Hub",
        "vision.hub.desc": "Destination between hills",
        "vision.network": "Skills Network",
        "vision.network.desc": "Talent meets opportunity",
        "vision.quote": "We are not waiting for access. We are building an economy first.",
        "cta.title": "Ready to be part of the story?",
        "cta.partner": "Partner With Us",
        "cta.story": "Read Our Story",
        "hub.title": "Sunlight Hub",
        "hub.subtitle": "Your community space. Share stories, celebrate wins, and stay connected with Seemana Gaon.",
        "hub.join": "Join the Community",
        "hub.explore": "Explore Spaces",
        "hub.explore.desc": "Find your corner of the village",
        "hub.enter": "Explore",
        "hub.creators": "Creators Corner",
        "hub.creators.desc": "Video makers, TikTokers & content creators showcasing village life",
        "hub.youth": "Young Voices",
        "hub.youth.desc": "Kids' artwork, school achievements & future talents of Sunaray",
        "hub.mothers": "Ama's Circle",
        "hub.mothers.desc": "Recipes, traditions & wisdom passed down through generations",
        "hub.fathers": "Bua's Guild",
        "hub.fathers.desc": "Construction, farming tips & mentorship from village builders",
        "hub.updates": "Development Notes",
        "hub.updates.desc": "Village announcements, schemes & community meetings",
        "hub.praises": "Praises & Pride",
        "hub.praises.desc": "Achievements, thank you notes & festival highlights",
        "hub.stats.members": "Members",
        "hub.stats.families": "Families",
        "hub.stats.stories": "Stories",
        "hub.personality": "Find My Personality",
        "hub.personality.desc": "Discover your true self with our village-style quiz!",
        "personality.title": "Village Personality Quiz",
        "personality.subtitle": "10 questions. Brutally honest results.",
        "personality.start": "Start Quiz",
        "personality.submit": "Reveal My True Self",
        "personality.retake": "Retake Quiz",
        "footer.tagline": "A living record of a small village in Lamahatta, Darjeeling. 22 houses. ~93 people. One story.",
        "footer.navigate": "Navigate",
        "footer.connected": "Stay Connected",
        "footer.connected.desc": "Local updates, government schemes, opportunities.",
        "footer.subscribe": "Subscribe to Updates →",
        "footer.credit": "A Living Record · Seemana Gaon, Lamahatta, Darjeeling",
        "footer.unfinished": "This site is not finished. Neither is the village.",
        "village.title": "The Village",
        "village.talent": "Talent",
        "village.subtitle": "Discover the creators, guides, and artisans that make Lamahatta special.",
        "village.noPortfolios": "No portfolios yet. Be the first!",
        "village.createPortfolio": "Create Your Portfolio",
        "common.loading": "Loading...",
        "common.partnerWithUs": "Partner With Us",
        "investor.label": "For Investors",
        "investor.title": "A Letter to You",
        "investor.greeting": "Dear Investor,",
        "investor.p1": "If you are looking for land to build a vacation home, homestay, restaurant, or retreat in the mountains of Darjeeling — we welcome you to Sunaray Gown.",
        "investor.p2": "Our village sits at the edge of Lamahatta, surrounded by pine forests and mountain views. We have 22 houses, 93 residents, and a community that values careful growth over quick money.",
        "investor.p3": "We are open to partnerships that respect our land, involve our people, and contribute to the local economy. Whether you want to build a boutique homestay, a small café, or simply own a piece of mountain peace — let's talk.",
        "investor.closing": "We remember who stood with us when we were small.",
        "investor.formTitle": "Interested in Investing?",
        "investor.phone": "Phone Number",
        "investor.interest": "What are you interested in?",
        "investor.placeholder": "E.g., Building a homestay, buying land, opening a café...",
        "investor.submit": "Contact Us",
        "investor.sending": "Sending...",
        "investor.success": "Thank you! We'll be in touch soon.",
        "investor.error": "Something went wrong. Please try again.",
        "investor.learn": "Learn More About Partnerships →",
        "partners.label": "Invest & Collaborate",
        "partners.title": "Work With Us",
        "partners.subtitle": "We are valuable because we serve genuinely, grow carefully, and remember.",
        "partners.genuine": "Genuine Service",
        "partners.genuine.desc": "We serve our community first",
        "partners.pride": "Local Pride",
        "partners.pride.desc": "We take pride in our work",
        "partners.growth": "Careful Growth",
        "partners.growth.desc": "We grow without losing identity",
        "partners.memory": "Long Memory",
        "partners.memory.desc": "We remember who stood with us",
        "partners.experience": "People who come here experience:",
        "partners.quote": "We do not sell spectacle. We build trust.",
        "partners.formTitle": "Interested in partnering?",
        "partners.formDesc": "Reach out for investment opportunities, collaborations, or visits.",
        "partners.phone": "Phone Number",
        "partners.message": "Message (optional)",
        "partners.messagePlaceholder": "Tell us how you'd like to collaborate...",
        "partners.submit": "Get In Touch",
        "partners.success": "Thank you! We'll get back to you soon.",
        "dashboard.loading": "Loading...",
        "dashboard.title": "Member Dashboard",
        "dashboard.adminTitle": "Admin Dashboard",
        "dashboard.welcome": "Welcome back",
        "dashboard.signOut": "Sign Out",
        "dashboard.role.villager": "Role: Worker / Villager",
        "dashboard.role.admin": "Role: Samaj Head / Admin",
        "dashboard.editPortfolio": "Edit Your Portfolio",
        "dashboard.previewTips": "Preview & Tips",
        "dashboard.tipsDesc": "Your portfolio helps visitors discover your talents. Make sure to:",
        "dashboard.tip1": "Choose a clear title (e.g., 'Homestay & Local Guide').",
        "dashboard.tip2": "Write a short but engaging bio.",
        "dashboard.tip3": "List your key skills or offerings.",
        "dashboard.tip4": "Update your contact info so people can reach you.",
        "dashboard.admin.pending": "Pending Approvals",
        "dashboard.admin.pendingDesc": "Review updates from villagers.",
        "dashboard.admin.noPending": "No pending items right now.",
        "dashboard.admin.users": "Manage Users",
        "dashboard.admin.usersDesc": "View registered villagers.",
        "dashboard.admin.inquiries": "Investor Inquiries",
        "dashboard.admin.inquiriesDesc": "Review partnership requests.",
        "nav.signIn": "Sign In",
        "account.overview": "Overview",
        "account.myHousehold": "My Household",
        "account.myRequests": "Update Requests",
        "account.directory": "Village Directory",
        "account.approvals": "Approvals",
        "account.manageHouseholds": "Manage Households",
        "account.signOut": "Sign Out",
        "account.adminRole": "Samaj Head",
        "account.villagerRole": "Villager"
    },
    NE: {
        "nav.home": "गृहपृष्ठ",
        "nav.why": "कथा",
        "nav.change": "परिवर्तन",
        "nav.economy": "अवसर",
        "nav.services": "सेवाहरू",
        "nav.challenges": "चुनौतीहरू",
        "nav.voices": "आवाजहरू",
        "nav.village": "प्रतिभा",
        "nav.hub": "हब",
        "nav.partners": "साझेदारहरू",
        "nav.updates": "अपडेटहरू",
        "hero.location": "लामाहट्टा · दार्जीलिङ",
        "hero.title": "सुनरे गाउन",
        "hero.subtitle": "संक्रमणमा रहेको गाउँले अर्थतन्त्र",
        "hero.houses": "घरहरू",
        "hero.residents": "बासिन्दाहरू",
        "hero.potential": "सम्भावना",
        "hero.scroll": "तल स्क्रोल गर्नुहोस् ↓",
        "hero.opportunity": "अवसर हेर्नुहोस्",
        "hero.story": "हाम्रो कथा",
        "hero.join": "गाउँमा सामेल हुनुहोस्",
        "hero.panorama.title": "फराकिलो क्षितिज",
        "hero.panorama.desc": "सीमा गाउँको हरेक कुना साझा इतिहास र वरपरका पहाडहरूको मनमोहक दृश्यले जोडिएको छ।",
        "hero.main_title": "सुनरे गाउँ केवल एउटा गाउँको वेबसाइट होइन।",
        "hero.main_subtitle": "यो एउटा जीवित गाउँले अर्थतन्त्रको मूल ढोका हो।",
        "opportunities.title": "अवसरहरू",
        "opportunities.villagers": "गाउँलेहरूको लागि",
        "opportunities.villagers.desc": "सेवा, योजना र अवसरहरू पहुँच गर्नुहोस्",
        "opportunities.investors": "लगानीकर्ताहरूको लागि",
        "opportunities.investors.desc": "अवसरको खाडल हेर्नुहोस्",
        "opportunities.partners": "साझेदारहरूको लागि",
        "opportunities.partners.desc": "हामीसँग सहयोग गर्नुहोस्",
        "opportunities.enter": "प्रवेश गर्नुहोस् →",
        "location.label": "स्थान",
        "location.title": "हामी कहाँ छौं",
        "location.subtitle": "६ माईल र ताकदाह बीचमा। पहाडमा लुकेको रत्न।",
        "location.satellite": "उपग्रह दृश्य",
        "location.houses": "जंगलमा बसेका २२ घरहरू",
        "location.maps": "Google Maps मा खोल्नुहोस् ↗",
        "life.quote": "राम्रो खाना। इमानदार आतिथ्य। हाँसो र न्यानोपन। आफ्नो महसुस।",
        "life.attribution": "— आगन्तुकहरूले यहाँ अनुभव गर्ने कुरा",
        "gaps.label": "लगानीकर्ताहरूको लागि",
        "gaps.title": "अवसरको खाडल",
        "gaps.subtitle": "उच्च माग। शून्य आपूर्ति। लगानीको लागि आदर्श।",
        "gaps.homestay": "होमस्टे",
        "gaps.cafe": "क्याफे",
        "gaps.guide": "गाइड",
        "gaps.organic": "जैविक खेती",
        "gaps.status": "खाडल",
        "gaps.potential": "होमस्टे सम्भावना: हिमाल दृश्य, प्रामाणिक अनुभव",
        "economy.label": "सक्रिय अर्थतन्त्र",
        "economy.title": "हामी के गर्छौं",
        "economy.subtitle": "खाना पकाउनेदेखि कोडिङसम्म। काम गर्ने गाउँले अर्थतन्त्र।",
        "economy.view": "सबै सेवाहरू हेर्नुहोस्",
        "economy.food": "खाना र आतिथ्य",
        "economy.agriculture": "कृषि",
        "economy.construction": "निर्माण",
        "economy.digital": "डिजिटल सेवाहरू",
        "economy.active": "सक्रिय",
        "vision.label": "दृष्टिकोण",
        "vision.title": "हामी के बनाउँदैछौं",
        "vision.portal": "गाउँ पोर्टल",
        "vision.portal.desc": "सबै सेवाहरूको लागि एक प्लेटफर्म",
        "vision.hub": "पर्यटन हब",
        "vision.hub.desc": "पहाडहरू बीचको गन्तव्य",
        "vision.network": "सीप नेटवर्क",
        "vision.network.desc": "प्रतिभाले अवसर भेट्छ",
        "vision.quote": "हामी पहुँचको लागि कुर्दैनौं। हामी पहिले अर्थतन्त्र बनाउँदैछौं।",
        "cta.title": "कथाको अंश बन्न तयार हुनुहुन्छ?",
        "cta.partner": "हामीसँग साझेदारी गर्नुहोस्",
        "cta.story": "हाम्रो कथा पढ्नुहोस्",
        "footer.tagline": "लामाहट्टा, दार्जीलिङको सानो गाउँको जीवित अभिलेख। २२ घर। ~९३ मानिस। एक कथा।",
        "footer.navigate": "नेभिगेट",
        "footer.connected": "जोडिइ रहनुहोस्",
        "footer.connected.desc": "स्थानीय अपडेट, सरकारी योजना, अवसरहरू।",
        "footer.subscribe": "अपडेटहरूमा सदस्यता लिनुहोस् →",
        "footer.credit": "जीवित अभिलेख · सुनरे गाउन, लामाहट्टा, दार्जीलिङ",
        "footer.unfinished": "यो साइट समाप्त भएको छैन। गाउँ पनि छैन।",
        "hub.title": "सनलाइट हब",
        "hub.subtitle": "तपाईंको समुदाय स्थान। कथाहरू साझा गर्नुहोस्, जितहरू मनाउनुहोस्, र सुनरे गाउनसँग जोडिइ रहनुहोस्।",
        "hub.join": "समुदायमा सामेल हुनुहोस्",
        "hub.explore": "स्थानहरू अन्वेषण गर्नुहोस्",
        "hub.explore.desc": "गाउँको आफ्नो कुना खोज्नुहोस्",
        "hub.enter": "अन्वेषण गर्नुहोस्",
        "hub.creators": "सिर्जकहरूको कुना",
        "hub.creators.desc": "गाउँको जीवन देखाउने भिडियो निर्माता, टिकटकर्स र सामग्री सिर्जकहरू",
        "hub.youth": "युवा आवाजहरू",
        "hub.youth.desc": "बालबालिकाको कला, विद्यालयका उपलब्धिहरू र सुनरेका भविष्यका प्रतिभाहरू",
        "hub.mothers": "आमाको सर्कल",
        "hub.mothers.desc": "परिकार, परम्पराहरू र ज्ञान पुस्तौं पुस्तासम्म सारिएका छन्",
        "hub.fathers": "बुवाको गिल्ड",
        "hub.fathers.desc": "गाउँ निर्माताहरूबाट निर्माण, खेती सुझावहरू र मार्गदर्शन",
        "hub.updates": "विकास नोटहरू",
        "hub.updates.desc": "गाउँ घोषणाहरू, योजनाहरू र सामुदायिक बैठकहरू",
        "hub.praises": "प्रशंसा र गौरव",
        "hub.praises.desc": "उपलब्धिहरू, धन्यवाद नोटहरू र चाड हाइलाइटहरू",
        "hub.stats.members": "सदस्यहरू",
        "hub.stats.families": "परिवारहरू",
        "hub.stats.stories": "कथाहरू",
        "hub.personality": "मेरो व्यक्तित्व खोज्नुहोस्",
        "hub.personality.desc": "हाम्रो गाउँ-शैली क्विजमार्फत आफ्नो साँचो स्वरूप पत्ता लगाउनुहोस्!",
        "personality.title": "गाउँ व्यक्तित्व क्विज",
        "personality.subtitle": "१० प्रश्न। निर्मम इमानदार परिणामहरू।",
        "personality.start": "क्विज सुरु गर्नुहोस्",
        "personality.submit": "मेरो साँचो स्वरूप खोल्नुहोस्",
        "personality.retake": "फेरि क्विज लिनुहोस्",
        "village.title": "गाउँ",
        "village.talent": "प्रतिभा",
        "village.subtitle": "लामाहट्टालाई विशेष बनाउने सिर्जक, गाइड र कारीगरहरू पत्ता लगाउनुहोस्।",
        "village.noPortfolios": "अहिले सम्म कुनै पोर्टफोलियो छैन। पहिलो बन्नुहोस्!",
        "village.createPortfolio": "आफ्नो पोर्टफोलियो बनाउनुहोस्",
        "common.loading": "लोड हुँदैछ...",
        "common.partnerWithUs": "हामीसँग साझेदारी गर्नुहोस्",
        "investor.label": "लगानीकर्ताहरूको लागि",
        "investor.title": "तपाईंलाई एउटा पत्र",
        "investor.greeting": "प्रिय लगानीकर्ता,",
        "investor.p1": "यदि तपाईं दार्जीलिङको पहाडमा भ्रमण घर, होमस्टे, रेस्टुरेन्ट, वा रिट्रीट बनाउन जमिन खोज्दै हुनुहुन्छ भने — सुनरे गाउनमा स्वागत छ।",
        "investor.p2": "हाम्रो गाउँ लामाहट्टाको छेउमा छ, पाइन जंगल र पहाडको दृश्यले घेरिएको छ। हामीसँग २२ घरहरू, ९३ बासिन्दाहरू, र छिटो पैसाभन्दा होसियार बृद्धिलाई महत्त्व दिने समुदाय छ।",
        "investor.p3": "हाम्रो जमिनलाई सम्मान गर्ने, हाम्रा मानिसहरूलाई संलग्न गराउने, र स्थानीय अर्थतन्त्रमा योगदान गर्ने साझेदारीमा हामी खुला छौं।",
        "investor.closing": "हामी सानो हुँदा हामीसँग उभिनेहरूलाई सम्झन्छौं।",
        "investor.formTitle": "लगानीमा रुचि छ?",
        "investor.phone": "फोन नम्बर",
        "investor.interest": "तपाईं के मा रुचि राख्नुहुन्छ?",
        "investor.submit": "सम्पर्क गर्नुहोस्",
        "investor.success": "धन्यवाद! हामी चाँडै सम्पर्कमा हुनेछौं।",
        "partners.label": "लगानी र सहयोग",
        "partners.title": "हामीसँग काम गर्नुहोस्",
        "partners.subtitle": "हामी साँच्चै सेवा गर्छौं, होसियारसँग बढ्छौं, र सम्झन्छौं।",
        "partners.experience": "यहाँ आउने मानिसहरूले अनुभव गर्छन्:",
        "partners.quote": "हामी तমাशा बेच्दैनौं। हामी विश्वास बनाउँछौं।",
        "partners.formTitle": "साझेदारीमा रुचि छ?",
        "partners.formDesc": "लगानी अवसरहरू, सहयोग, वा भ्रमणको लागि सम्पर्क गर्नुहोस्।",
        "partners.submit": "सम्पर्क गर्नुहोस्",
        "partners.success": "धन्यवाद! हामी चाँडै जवाफ दिनेछौं।",
        "dashboard.loading": "लोड हुँदैछ...",
        "dashboard.title": "सदस्य ड्यासबोर्ड",
        "dashboard.adminTitle": "प्रशासक ड्यासबोर्ड",
        "dashboard.welcome": "फेरि स्वागत छ",
        "dashboard.signOut": "साइन आउट गर्नुहोस्",
        "dashboard.role.villager": "भूमिका: कामदार / गाउँले",
        "dashboard.role.admin": "भूमिका: समाज प्रमुख / प्रशासक",
        "dashboard.editPortfolio": "आफ्नो पोर्टफोलियो सम्पादन गर्नुहोस्",
        "dashboard.previewTips": "पूर्वावलोकन र सुझावहरू",
        "dashboard.tipsDesc": "तपाईंको पोर्टफोलियोले आगन्तुकहरूलाई तपाईंको प्रतिभा पत्ता लगाउन मद्दत गर्दछ। सुनिश्चित गर्नुहोस्:",
        "dashboard.tip1": "स्पष्ट शीर्षक छान्नुहोस् (जस्तै, 'होमस्टे र स्थानीय गाइड')।",
        "dashboard.tip2": "छोटो तर आकर्षक बायो लेख्नुहोस्।",
        "dashboard.tip3": "तपाईंका मुख्य सीपहरू वा प्रस्तावहरू सूचीबद्ध गर्नुहोस्।",
        "dashboard.tip4": "तपाईंको सम्पर्क जानकारी अपडेट गर्नुहोस् ताकि मानिसहरू तपाईंलाई सम्पर्क गर्न सकून्।",
        "dashboard.admin.pending": "बाँकी अनुमोदनहरू",
        "dashboard.admin.pendingDesc": "गाउँलेहरूबाट अपडेटहरू समीक्षा गर्नुहोस्।",
        "dashboard.admin.noPending": "अहिले कुनै पनि बाँकी वस्तुहरू छैनन्।",
        "dashboard.admin.users": "प्रयोगकर्ताहरू प्रबन्ध गर्नुहोस्",
        "dashboard.admin.usersDesc": "दर्ता गरिएका गाउँलेहरू हेर्नुहोस्।",
        "dashboard.admin.inquiries": "लगानीकर्ता सोधपुछ",
        "dashboard.admin.inquiriesDesc": "साझेदारी अनुरोधहरू समीक्षा गर्नुहोस्।",
        "nav.signIn": "साइन इन",
        "account.overview": "सिंहावलोकन",
        "account.myHousehold": "मेरो परिवार",
        "account.myRequests": "अपडेट अनुरोधहरू",
        "account.directory": "गाउँ निर्देशिका",
        "account.approvals": "स्वीकृतिहरू",
        "account.manageHouseholds": "परिवार व्यवस्थापन",
        "account.signOut": "साइन आउट",
        "account.adminRole": "समाज प्रमुख",
        "account.villagerRole": "गाउँले"
    },
    HI: {
        "nav.home": "होम",
        "nav.why": "यह क्यों मौजूद है",
        "nav.change": "बदलाव",
        "nav.economy": "हम क्या करते हैं",
        "nav.services": "सेवाएँ",
        "nav.challenges": "चुनौतियाँ",
        "nav.voices": "आवाज़ें",
        "nav.partners": "भागीदार",
        "nav.updates": "अपडेट",
        "hero.location": "लामाहट्टा · दार्जीलिंग",
        "hero.title": "सुनरे गाउन",
        "hero.subtitle": "संक्रमण में एक गाँव की अर्थव्यवस्था",
        "hero.houses": "घर",
        "hero.residents": "निवासी",
        "hero.potential": "संभावना",
        "hero.scroll": "नीचे स्क्रॉल करें ↓",
        "hero.opportunity": "अवसर देखें",
        "hero.story": "हमारी कहानी",
        "opportunities.title": "अवसर",
        "opportunities.villagers": "ग्रामीणों के लिए",
        "opportunities.villagers.desc": "सेवाएं, योजनाएं और अवसर प्राप्त करें",
        "opportunities.investors": "निवेशकों के लिए",
        "opportunities.investors.desc": "अवसर की खाई देखें",
        "opportunities.partners": "भागीदारों के लिए",
        "opportunities.partners.desc": "हमारे साथ सहयोग करें",
        "opportunities.enter": "प्रवेश →",
        "location.label": "स्थान",
        "location.title": "हम कहाँ हैं",
        "location.subtitle": "6वें माइल और ताकदाह के बीच। पहाड़ों में छिपा हुआ रत्न।",
        "location.satellite": "उपग्रह दृश्य",
        "location.houses": "जंगल में बसे 22 घर",
        "location.maps": "Google Maps में खोलें ↗",
        "life.quote": "अच्छा खाना। ईमानदार मेहमाननवाज़ी। हास्य और गर्मजोशी। अपनापन।",
        "life.attribution": "— आगंतुक यहाँ क्या अनुभव करते हैं",
        "gaps.label": "निवेशकों के लिए",
        "gaps.title": "अवसर की खाई",
        "gaps.subtitle": "उच्च मांग। शून्य आपूर्ति। निवेश के लिए आदर्श।",
        "gaps.homestay": "होमस्टे",
        "gaps.cafe": "कैफे",
        "gaps.guide": "गाइड",
        "gaps.organic": "जैविक खेती",
        "gaps.status": "खाई",
        "gaps.potential": "होमस्टे क्षमता: पहाड़ी दृश्य, प्रामाणिक अनुभव",
        "economy.label": "सक्रिय अर्थव्यवस्था",
        "economy.title": "हम क्या करते हैं",
        "economy.subtitle": "खाना बनाने से कोडिंग तक। एक कामकाजी गाँव अर्थव्यवस्था।",
        "economy.view": "सभी सेवाएं देखें",
        "economy.food": "खाना और मेहमाननवाज़ी",
        "economy.agriculture": "कृषि",
        "economy.construction": "निर्माण",
        "economy.digital": "डिजिटल सेवाएं",
        "economy.active": "सक्रिय",
        "vision.label": "दृष्टि",
        "vision.title": "हम क्या बना रहे हैं",
        "vision.portal": "गाँव पोर्टल",
        "vision.portal.desc": "सभी सेवाओं के लिए एक प्लेटफॉर्म",
        "vision.hub": "पर्यटन हब",
        "vision.hub.desc": "पहाड़ियों के बीच गंतव्य",
        "vision.network": "कौशल नेटवर्क",
        "vision.network.desc": "प्रतिभा अवसर से मिलती है",
        "vision.quote": "हम पहुँच का इंतज़ार नहीं कर रहे। हम पहले अर्थव्यवस्था बना रहे हैं।",
        "cta.title": "कहानी का हिस्सा बनने के लिए तैयार?",
        "cta.partner": "हमारे साथ भागीदारी करें",
        "cta.story": "हमारी कहानी पढ़ें",
        "footer.tagline": "लामाहट्टा, दार्जीलिंग के एक छोटे गाँव का जीवित रिकॉर्ड। 22 घर। ~93 लोग। एक कहानी।",
        "footer.navigate": "नेविगेट",
        "footer.connected": "जुड़े रहें",
        "footer.connected.desc": "स्थानीय अपडेट, सरकारी योजनाएं, अवसर।",
        "footer.subscribe": "अपडेट के लिए सदस्यता लें →",
        "footer.credit": "जीवित रिकॉर्ड · सुनरे गाउन, लामाहट्टा, दार्जीलिंग",
        "footer.unfinished": "यह साइट पूरी नहीं हुई है। न ही गाँव।",
        "hub.title": "सनलाइट हब",
        "hub.subtitle": "आपका सामुदायिक स्थान। कहानियाँ साझा करें, जीत का जश्न मनाएं, और सुनरे गाउन से जुड़े रहें।",
        "hub.join": "समुदाय में शामिल हों",
        "hub.explore": "स्थानों का अन्वेषण करें",
        "hub.explore.desc": "गाँव में अपना कोना खोजें",
        "hub.enter": "अन्वेषण करें",
        "hub.creators": "क्रिएटर्स कॉर्नर",
        "hub.creators.desc": "गाँव की जिंदगी दिखाने वाले वीडियो मेकर्स, टिकटॉकर्स और कंटेंट क्रिएटर्स",
        "hub.youth": "युवा आवाजें",
        "hub.youth.desc": "बच्चों की कला, स्कूल की उपलब्धियाँ और सुनरे की भविष्य की प्रतिभाएं",
        "hub.mothers": "माँ का सर्कल",
        "hub.mothers.desc": "पीढ़ियों से चली आ रही रेसिपी, परंपराएं और ज्ञान",
        "hub.fathers": "पिता का गिल्ड",
        "hub.fathers.desc": "गाँव के निर्माताओं से निर्माण, खेती की सलाह और मार्गदर्शन",
        "hub.updates": "विकास नोट्स",
        "hub.updates.desc": "गाँव की घोषणाएं, योजनाएं और सामुदायिक बैठकें",
        "hub.praises": "प्रशंसा और गौरव",
        "hub.praises.desc": "उपलब्धियाँ, धन्यवाद नोट्स और त्योहार हाइलाइट्स",
        "hub.stats.members": "सदस्य",
        "hub.stats.families": "परिवार",
        "hub.stats.stories": "कहानियाँ",
        "hub.personality": "मेरा व्यक्तित्व खोजें",
        "hub.personality.desc": "हमारी गाँव-शैली क्विज से अपना असली स्वरूप जानें!",
        "personality.title": "गाँव व्यक्तित्व क्विज",
        "personality.subtitle": "10 सवाल। बेरहमी से ईमानदार परिणाम।",
        "personality.start": "क्विज शुरू करें",
        "personality.submit": "मेरा असली स्वरूप दिखाएं",
        "personality.retake": "क्विज फिर से लें",
        "village.title": "गाँव",
        "village.talent": "प्रतिभा",
        "village.subtitle": "उन रचनाकारों, गाइडों और कारीगरों की खोज करें जो लामाहट्टा को खास बनाते हैं।",
        "village.noPortfolios": "अभी तक कोई पोर्टफोलियो नहीं। पहले बनें!",
        "village.createPortfolio": "अपना पोर्टफोलियो बनाएं",
        "common.loading": "लोड हो रहा है...",
        "common.partnerWithUs": "हमारे साथ भागीदारी करें",
        "investor.label": "निवेशकों के लिए",
        "investor.title": "आपके लिए एक पत्र",
        "investor.greeting": "प्रिय निवेशक,",
        "investor.p1": "यदि आप दार्जीलिंग की पहाड़ियों में छुट्टियों का घर, होमस्टे, रेस्तरां, या रिट्रीट बनाने के लिए जमीन ढूंढ रहे हैं — सुनरे गाउन में आपका स्वागत है।",
        "investor.p2": "हमारा गाँव लामाहट्टा के किनारे पर है, पाइन के जंगलों और पहाड़ी दृश्यों से घिरा हुआ। हमारे पास 22 घर, 93 निवासी, और एक समुदाय है जो तेज पैसे से ज्यादा सावधानीपूर्ण विकास को महत्व देता है।",
        "investor.p3": "हम उन साझेदारियों के लिए खुले हैं जो हमारी जमीन का सम्मान करती हैं, हमारे लोगों को शामिल करती हैं, और स्थानीय अर्थव्यवस्था में योगदान देती हैं।",
        "investor.closing": "हम उन्हें याद रखते हैं जो हमारे छोटे होने पर हमारे साथ खड़े थे।",
        "investor.formTitle": "निवेश में रुचि है?",
        "investor.phone": "फोन नंबर",
        "investor.interest": "आप किसमें रुचि रखते हैं?",
        "investor.submit": "संपर्क करें",
        "investor.success": "धन्यवाद! हम जल्द ही संपर्क करेंगे।",
        "partners.label": "निवेश और सहयोग",
        "partners.title": "हमारे साथ काम करें",
        "partners.subtitle": "हम सच्ची सेवा करते हैं, सावधानी से बढ़ते हैं, और याद रखते हैं।",
        "partners.experience": "यहाँ आने वाले लोग अनुभव करते हैं:",
        "partners.quote": "हम तमाशा नहीं बेचते। हम विश्वास बनाते हैं।",
        "partners.formTitle": "साझेदारी में रुचि है?",
        "partners.formDesc": "निवेश अवसरों, सहयोग, या यात्राओं के लिए संपर्क करें।",
        "partners.submit": "संपर्क करें",
        "partners.success": "धन्यवाद! हम जल्द जवाब देंगे।",
        "dashboard.loading": "लोड हो रहा है...",
        "dashboard.title": "सदस्य डैशबोर्ड",
        "dashboard.adminTitle": "व्यवस्थापक डैशबोर्ड",
        "dashboard.welcome": "वापसी पर स्वागत है",
        "dashboard.signOut": "साइन आउट करें",
        "dashboard.role.villager": "भूमिका: कार्यकर्ता / ग्रामीण",
        "dashboard.role.admin": "भूमिका: समाज प्रमुख / व्यवस्थापक",
        "dashboard.editPortfolio": "अपना पोर्टफोलियो संपादित करें",
        "dashboard.previewTips": "पूर्वावलोकन और सुझाव",
        "dashboard.tipsDesc": "आपका पोर्टफोलियो आगंतुकों को आपकी प्रतिभाओं को खोजने में मदद करता है। सुनिश्चित करें:",
        "dashboard.tip1": "एक स्पष्ट शीर्षक चुनें (जैसे, 'होमस्टे और स्थानीय गाइड')।",
        "dashboard.tip2": "एक छोटा लेकिन आकर्षक परिचय लिखें।",
        "dashboard.tip3": "अपने प्रमुख कौशल या प्रसादों की सूची बनाएं।",
        "dashboard.tip4": "अपनी संपर्क जानकारी अपडेट करें ताकि लोग आप तक पहुंच सकें।",
        "dashboard.admin.pending": "लंबित स्वीकृतियाँ",
        "dashboard.admin.pendingDesc": "ग्रामीणों से अपडेट की समीक्षा करें।",
        "dashboard.admin.noPending": "अभी कोई लंबित आइटम नहीं है।",
        "dashboard.admin.users": "उपयोगकर्ताओं का प्रबंधन करें",
        "dashboard.admin.usersDesc": "पंजीकृत ग्रामीणों को देखें।",
        "dashboard.admin.inquiries": "निवेशक पूछताछ",
        "dashboard.admin.inquiriesDesc": "साझेदारी अनुरोधों की समीक्षा करें।",
        "nav.signIn": "साइन इन",
        "account.overview": "अवलोकन",
        "account.myHousehold": "मेरा परिवार",
        "account.myRequests": "अपडेट अनुरोध",
        "account.directory": "गाँव निर्देशिका",
        "account.approvals": "स्वीकृतियाँ",
        "account.manageHouseholds": "परिवार प्रबंधन",
        "account.signOut": "साइन आउट",
        "account.adminRole": "समाज प्रमुख",
        "account.villagerRole": "ग्रामीण"
    },
    BN: {
        "nav.home": "হোম",
        "nav.why": "এটি কেন বিদ্যমান",
        "nav.change": "পরিবর্তন",
        "nav.economy": "আমরা কী করি",
        "nav.services": "পরিষেবা",
        "nav.challenges": "চ্যালেঞ্জ",
        "nav.voices": "কণ্ঠস্বর",
        "nav.partners": "অংশীদার",
        "nav.updates": "আপডেট",
        "hero.location": "লামাহাট্টা · দার্জিলিং",
        "hero.title": "সুনরে গাউন",
        "hero.subtitle": "রূপান্তরে একটি গ্রাম অর্থনীতি",
        "hero.houses": "বাড়ি",
        "hero.residents": "বাসিন্দা",
        "hero.potential": "সম্ভাবনা",
        "hero.scroll": "নিচে স্ক্রোল করুন ↓",
        "hero.opportunity": "সুযোগ দেখুন",
        "hero.story": "আমাদের গল্প",
        "opportunities.title": "সুযোগ",
        "opportunities.villagers": "গ্রামবাসীদের জন্য",
        "opportunities.villagers.desc": "পরিষেবা, স্কিম এবং সুযোগ অ্যাক্সেส করুন",
        "opportunities.investors": "বিনিয়োগকারীদের জন্য",
        "opportunities.investors.desc": "সুযোগের ফাঁক দেখুন",
        "opportunities.partners": "অংশীদারদের জন্য",
        "opportunities.partners.desc": "আমাদের সাথে সহযোগিতা করুন",
        "opportunities.enter": "প্রবেশ করুন →",
        "location.label": "অবস্থান",
        "location.title": "আমরা কোথায় আছি",
        "location.subtitle": "৬ষ্ঠ মাইল এবং তাকদাহের মধ্যে। পাহাড়ে লুকানো রত্ন।",
        "location.satellite": "স্যাটেলাইট ভিউ",
        "location.houses": "বনের মধ্যে ২২টি বাড়ি",
        "location.maps": "Google Maps এ খুলুন ↗",
        "life.quote": "ভালো খাবার। সৎ আতিথেয়তা। হাস্যরস এবং উষ্ণতা। আপনত্বের অনুভূতি।",
        "life.attribution": "— দর্শনার্থীরা এখানে যা অনুভব করেন",
        "gaps.label": "বিনিয়োগকারীদের জন্য",
        "gaps.title": "সুযোগের ফাঁক",
        "gaps.subtitle": "উচ্চ চাহিদা। শূন্য সরবরাহ। বিনিয়োগের জন্য আদর্শ।",
        "gaps.homestay": "হোমস্টে",
        "gaps.cafe": "ক্যাফে",
        "gaps.guide": "গাইড",
        "gaps.organic": "জৈব চাষ",
        "gaps.status": "ফাঁক",
        "gaps.potential": "হোমস্টে সম্ভাবনা: পাহাড়ের দৃশ্য, প্রামাণিক অভিজ্ঞতা",
        "economy.label": "সক্রিয় অর্থনীতি",
        "economy.title": "আমরা কী করি",
        "economy.subtitle": "রান্না থেকে কোডিং পর্যন্ত। একটি কর্মক্ষম গ্রাম অর্থনীতি।",
        "economy.view": "সব পরিষেবা দেখুন",
        "economy.food": "খাবার ও আতিথেয়তা",
        "economy.agriculture": "কৃষি",
        "economy.construction": "নির্মাণ",
        "economy.digital": "ডিজিটাল পরিষেবা",
        "economy.active": "সক্রিয়",
        "vision.label": "দৃষ্টি",
        "vision.title": "আমরা কী বানাচ্ছি",
        "vision.portal": "গ্রাম পোর্টাল",
        "vision.portal.desc": "সব পরিষেবার জন্য এক প্ল্যাটফর্ম",
        "vision.hub": "পর্যটন হাব",
        "vision.hub.desc": "পাহাড়ের মধ্যে গন্তব্য",
        "vision.network": "দক্ষতা নেটওয়ার্ক",
        "vision.network.desc": "প্রতিভা সুযোগের সাথে মিলিত হয়",
        "vision.quote": "আমরা অ্যাক্সেসের জন্য অপেক্ষা করছি না। আমরা প্রথমে অর্থনীতি তৈরি করছি।",
        "cta.title": "গল্পের অংশ হতে প্রস্তুত?",
        "cta.partner": "আমাদের সাথে অংশীদার হন",
        "cta.story": "আমাদের গল্প পড়ুন",
        "footer.tagline": "লামাহাট্টা, দার্জিলিংয়ের একটি ছোট গ্রামের জীবন্ত রেকর্ড। ২২টি বাড়ি। ~৯৩ জন। একটি গল্প।",
        "footer.navigate": "নেভিগেট",
        "footer.connected": "সংযুক্ত থাকুন",
        "footer.connected.desc": "স্থানীয় আপডেট, সরকারি স্কিম, সুযোগ।",
        "footer.subscribe": "আপডেটের জন্য সাবস্ক্রাইব করুন →",
        "footer.credit": "জীবন্ত রেকর্ড · सुनरे गाउन, লামাহাট্টা, দার্জিলিং",
        "footer.unfinished": "এই সাইট শেষ হয়নি। গ্রামও না।",
        "hub.title": "সানলাইট হাব",
        "hub.subtitle": "আপনার কমিউনিটি স্পেস। গল্প শেয়ার করুন, জয় উদযাপন করুন, และ সুনরে গাউনের সাথে সংযুক্ত থাকুন।",
        "hub.join": "কমিউনিটিতে যোগ দিন",
        "hub.explore": "স্থানগুলো অন্বেষণ করুন",
        "hub.explore.desc": "গ্রামে আপনার কোণ খুঁজুন",
        "hub.enter": "অন্বেষণ করুন",
        "hub.creators": "ক্রিয়েটর্স কর্নার",
        "hub.creators.desc": "গ্রামের জীবন দেখানো ভিডিও মেকার, টিকটকার এবং কনটেন্ট ক্রিয়েটর",
        "hub.youth": "তরুণ কণ্ঠ",
        "hub.youth.desc": "শিশুদের শিল্প, স্কুলের অর্জন এবং সুনরের ভবিষ্যত প্রতিভা",
        "hub.mothers": "মায়ের সার্কেল",
        "hub.mothers.desc": "প্রজন্ম থেকে প্রজন্মে চলে আসা রেসিপি, ঐতিহ্য এবং জ্ঞান",
        "hub.fathers": "বাবার গিল্ড",
        "hub.fathers.desc": "গ্রামের নির্মাতাদের কাছ থেকে নির্মাণ, চাষের টিপส এবং পরামর্শ",
        "hub.updates": "উন্নয়ন নোট",
        "hub.updates.desc": "গ্রামের ঘোষণা, স্কিম এবং কমিউনিটি মিটিং",
        "hub.praises": "প্রশংসা ও গর্ব",
        "hub.praises.desc": "অর্জন, ধন্যবাদ নোট এবং উৎসবের হাইলাইট",
        "hub.stats.members": "সদস্য",
        "hub.stats.families": "পরিবার",
        "hub.stats.stories": "গল্প",
        "hub.personality": "আমার ব্যক্তিত্ব খুঁজুন",
        "hub.personality.desc": "আমাদের গ্রাম-স্টাইল কুইজ দিয়ে আপনার প্রকৃত স্বরূপ আবিষ্কার করুন!",
        "personality.title": "গ্রাম ব্যক্তিত্ব কুইজ",
        "personality.subtitle": "১০টি প্রশ্ন। নির্মম সৎ ফলাফল।",
        "personality.start": "কুইজ শুরু করুন",
        "personality.submit": "আমার প্রকৃত স্বরূপ দেখান",
        "personality.retake": "আবার কুইজ নিন",
        "village.title": "গ্রাম",
        "village.talent": "প্রতিভা",
        "village.subtitle": "লামাহাট্টাকে বিশেষ করে তোলা সৃষ্টিকর্তা, গাইড এবং কারিগরদের আবিষ্কার করুন।",
        "village.noPortfolios": "এখনও কোনো পোর্টফোলিও নেই। প্রথম হন!",
        "village.createPortfolio": "আপনার পোর্টফোলিও তৈরি করুন",
        "common.loading": "লোড হচ্ছে...",
        "common.partnerWithUs": "আমাদের সাথে অংশীদার হন",
        "investor.label": "বিনিয়োগকারীদের জন্য",
        "investor.title": "আপনার জন্য একটি চিঠি",
        "investor.greeting": "প্রিয় বিনিয়োগকারী,",
        "investor.p1": "আপনি যদি দার্জিলিংয়ের পাহাড়ে ছুটির বাড়ি, হোমস্টে, রেস্তোরাঁ বা রিট্রিট তৈরি করতে জমি খুঁজছেন — সুনরে গাউনে স্বাগতম।",
        "investor.p2": "আমাদের গ্রাম লামাহাট্টার প্রান্তে, পাইন বন এবং পাহাড়ি দৃশ্য দ্বারা বেষ্টিত। আমাদের ২২টি বাড়ি, ৯৩ জন বাসিন্দা এবং দ্রুত টাকার চেয়ে সতর্ক বৃদ্ধিকে মূল্য দেওয়া একটি সম্প্রদায় আছে।",
        "investor.p3": "আমাদের জমিকে সম্মান করে, আমাদের মানুষদের জড়িত করে এবং স্থানীয় অর্থনীতিতে অবদান রাখে এমন অংশীদারিত্বে আমরা উন্মুক্ত।",
        "investor.closing": "আমরা মনে রাখি কারা আমাদের ছোট থাকতে পাশে দাঁড়িয়েছিল।",
        "investor.formTitle": "বিনিয়োগে আগ্রহী?",
        "investor.phone": "ফোন নম্বর",
        "investor.interest": "আপনি কিসে আগ্রহী?",
        "investor.submit": "যোগাযোগ করুন",
        "investor.success": "ধন্যবাদ! আমরা শীঘ্রই যোগাযোগ করব।",
        "partners.label": "বিনিয়োগ ও সহযোগিতা",
        "partners.title": "আমাদের সাথে কাজ করুন",
        "partners.subtitle": "আমরা সত্যিকারের সেবা করি, সতর্কভাবে বাড়ি এবং মনে রাখি।",
        "partners.experience": "এখানে আসা মানুষরা অভিজ্ঞতা করেন:",
        "partners.quote": "আমরা দর্শনীয়তা বিক্রি করি না। আমরা বিশ্বাস তৈরি করি।",
        "partners.formTitle": "অংশীদারিত্বে আগ্রহী?",
        "partners.formDesc": "বিনিয়োগ সুযোগ, সহযোগিতা বা পরিদর্শনের জন্য যোগাযোগ করুন।",
        "partners.submit": "যোগাযোগ করুন",
        "partners.success": "ধন্যবাদ! আমরা শীঘ্রই উত্তর দেব।",
        "dashboard.loading": "লোড হচ্ছে...",
        "dashboard.title": "সদস্য ড্যাশবোর্ড",
        "dashboard.adminTitle": "অ্যাডমিন ড্যাশবোর্ড",
        "dashboard.welcome": "আবার স্বাগতম",
        "dashboard.signOut": "সাইন আউট করুন",
        "dashboard.role.villager": "ভূমিকা: কর্মী / গ্রামবাসী",
        "dashboard.role.admin": "ভূমিকা: সমাজ প্রধান / অ্যাডমিন",
        "dashboard.editPortfolio": "আপনার পোর্টফোলিও সম্পাদনা করুন",
        "dashboard.previewTips": "প্রাকদর্শন এবং টিপস",
        "dashboard.tipsDesc": "আপনার পোর্টফোলিও দর্শকদের আপনার প্রতিভা আবিষ্কার করতে সাহায্য করে। নিশ্চিত করুন:",
        "dashboard.tip1": "একটি স্পষ্ট শিরোনাম চয়ন করুন (যেমন, 'হোমস্টে এবং স্থানীয় গাইড')।",
        "dashboard.tip2": "একটি ছোট কিন্তু আকর্ষণীয় জীবনী লিখুন।",
        "dashboard.tip3": "আপনার মূল দক্ষতা বা অফারগুলি তালিকাভুক্ত করুন।",
        "dashboard.tip4": "আপনার যোগাযোগের তথ্য আপডেট করুন যাতে মানুষ আপনার কাছে পৌঁছাতে পারে।",
        "dashboard.admin.pending": "অপেক্ষমাণ অনুমোদন",
        "dashboard.admin.pendingDesc": "গ্রামবাসীদের আপডেট পর্যালোচনা করুন।",
        "dashboard.admin.noPending": "এখন কোনো অপেক্ষমাণ আইটেম নেই।",
        "dashboard.admin.users": "ব্যবহারকারী পরিচালনা করুন",
        "dashboard.admin.usersDesc": "নিবন্ধিত গ্রামবাসীদের দেখুন।",
        "dashboard.admin.inquiries": "বিনিয়োগকারী অনুসন্ধান",
        "dashboard.admin.inquiriesDesc": "অংশীদারিত্বের অনুরোধ পর্যালোচনা করুন।",
        "nav.signIn": "সাইন ইন",
        "account.overview": "সারসংক্ষেপ",
        "account.myHousehold": "আমার পরিবার",
        "account.myRequests": "আপডেট অনুরোধ",
        "account.directory": "গ্রাম তালিকা",
        "account.approvals": "অনুমোদন",
        "account.manageHouseholds": "পরিবার ব্যবস্থাপনা",
        "account.signOut": "সাইন আউট",
        "account.adminRole": "সমাজ প্রধান",
        "account.villagerRole": "গ্রামবাসী"
    }
};

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
    const [language, setLanguage] = useState<Language>("EN");

    const t = (key: string): string => {
        return translations[language]?.[key] || translations["EN"]?.[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};
