"use client";

import React, { createContext, useContext, useState } from "react";

export type Language = "EN" | "NE" | "HI" | "BN" | "DZ" | "TB" | "SH" | "ZH" | "TH" | "FR";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
};

// Comprehensive translations for all site content
const translations: Record<Language, Record<string, string>> = {
    EN: {
        // Navigation
        "nav.home": "Home",
        "nav.why": "Why This Exists",
        "nav.change": "Change",
        "nav.economy": "What We Do",
        "nav.challenges": "Challenges",
        "nav.voices": "Voices",
        "nav.partners": "Partners",
        "nav.updates": "Updates",

        // Hero Section
        "hero.location": "Lamahatta · Darjeeling",
        "hero.title": "Sunaray Gown",
        "hero.subtitle": "A village economy in transition",
        "hero.houses": "Houses",
        "hero.residents": "Residents",
        "hero.potential": "Potential",
        "hero.scroll": "Scroll to explore ↓",
        "hero.opportunity": "See the Opportunity",
        "hero.story": "Our Story",

        // Opportunities Section
        "opportunities.title": "Opportunities",
        "opportunities.villagers": "For Villagers",
        "opportunities.villagers.desc": "Access services, schemes & opportunities",
        "opportunities.investors": "For Investors",
        "opportunities.investors.desc": "See the opportunity gaps",
        "opportunities.partners": "For Partners",
        "opportunities.partners.desc": "Collaborate with us",
        "opportunities.enter": "Enter →",

        // Location Section
        "location.label": "Location",
        "location.title": "Where We Are",
        "location.subtitle": "Between 6th Mile and Takdah. A hidden gem in the hills.",
        "location.satellite": "Satellite View",
        "location.houses": "22 Houses nestled in the forest",
        "location.maps": "Open in Google Maps ↗",

        // Village Life
        "life.quote": "Good food. Honest hospitality. Humor and warmth. A sense of belonging.",
        "life.attribution": "— What visitors experience here",

        // Opportunity Gaps
        "gaps.label": "For Investors",
        "gaps.title": "Opportunity Gaps",
        "gaps.subtitle": "High demand. Zero supply. Ideal for investment.",
        "gaps.homestay": "Homestay",
        "gaps.cafe": "Cafe",
        "gaps.guide": "Guide",
        "gaps.organic": "Organic Farm",
        "gaps.status": "Gap",
        "gaps.potential": "Homestay Potential: Mountain views, authentic experience",

        // Economy
        "economy.label": "Active Economy",
        "economy.title": "What We Do",
        "economy.subtitle": "From cooking to coding. A working village economy.",
        "economy.view": "View All Services",
        "economy.food": "Food & Hospitality",
        "economy.agriculture": "Agriculture",
        "economy.construction": "Construction",
        "economy.digital": "Digital Services",
        "economy.active": "active",

        // Vision
        "vision.label": "The Vision",
        "vision.title": "What We're Building",
        "vision.portal": "Village Portal",
        "vision.portal.desc": "One platform for all services",
        "vision.hub": "Tourism Hub",
        "vision.hub.desc": "Destination between hills",
        "vision.network": "Skills Network",
        "vision.network.desc": "Talent meets opportunity",
        "vision.quote": "We are not waiting for access. We are building an economy first.",

        // CTA
        "cta.title": "Ready to be part of the story?",
        "cta.partner": "Partner With Us",
        "cta.story": "Read Our Story",

        // Sunlight Hub
        "hub.title": "Sunlight Hub",
        "hub.subtitle": "Your community space. Share stories, celebrate wins, and stay connected with Sunaray Gown.",
        "hub.join": "Join the Community",
        "hub.explore": "Explore Spaces",
        "hub.explore.desc": "Find your corner of the village",
        "hub.enter": "Explore",
        "hub.creators": "Creators Corner",
        "hub.creators.desc": "Video makers, TikTokers & content creators showcasing village life",
        "hub.youth": "Young Voices",
        "hub.youth.desc": "Kids' artwork, school achievements & future talents of Sunaray",
        "hub.mothers": "Ama's Circle",
        "hub.mothers.desc": "Recipes, traditions & wisdom passed down through generations",
        "hub.fathers": "Bua's Guild",
        "hub.fathers.desc": "Construction, farming tips & mentorship from village builders",
        "hub.updates": "Development Notes",
        "hub.updates.desc": "Village announcements, schemes & community meetings",
        "hub.praises": "Praises & Pride",
        "hub.praises.desc": "Achievements, thank you notes & festival highlights",
        "hub.stats.members": "Members",
        "hub.stats.families": "Families",
        "hub.stats.stories": "Stories",

        // Personality Test
        "hub.personality": "Find My Personality",
        "hub.personality.desc": "Discover your true self with our village-style quiz!",
        "personality.title": "Village Personality Quiz",
        "personality.subtitle": "10 questions. Brutally honest results.",
        "personality.start": "Start Quiz",
        "personality.submit": "Reveal My True Self",
        "personality.retake": "Retake Quiz",

        // Footer
        "footer.tagline": "A living record of a small village in Lamahatta, Darjeeling. 22 houses. ~93 people. One story.",
        "footer.navigate": "Navigate",
        "footer.connected": "Stay Connected",
        "footer.connected.desc": "Local updates, government schemes, opportunities.",
        "footer.subscribe": "Subscribe to Updates →",
        "footer.credit": "A Living Record · Sunaray Gown, Lamahatta, Darjeeling",
        "footer.unfinished": "This site is not finished. Neither is the village.",
    },

    NE: {
        // Navigation
        "nav.home": "गृहपृष्ठ",
        "nav.why": "किन यो अस्तित्वमा छ",
        "nav.change": "परिवर्तन",
        "nav.economy": "हामी के गर्छौं",
        "nav.challenges": "चुनौतीहरू",
        "nav.voices": "आवाजहरू",
        "nav.partners": "साझेदारहरू",
        "nav.updates": "अपडेटहरू",

        // Hero
        "hero.location": "लामाहट्टा · दार्जीलिङ",
        "hero.title": "सुनरे गाउन",
        "hero.subtitle": "संक्रमणमा रहेको गाउँले अर्थतन्त्र",
        "hero.houses": "घरहरू",
        "hero.residents": "बासिन्दाहरू",
        "hero.potential": "सम्भावना",
        "hero.scroll": "तल स्क्रोल गर्नुहोस् ↓",
        "hero.opportunity": "अवसर हेर्नुहोस्",
        "hero.story": "हाम्रो कथा",

        // Opportunities
        "opportunities.title": "अवसरहरू",
        "opportunities.villagers": "गाउँलेहरूको लागि",
        "opportunities.villagers.desc": "सेवा, योजना र अवसरहरू पहुँच गर्नुहोस्",
        "opportunities.investors": "लगानीकर्ताहरूको लागि",
        "opportunities.investors.desc": "अवसरको खाडल हेर्नुहोस्",
        "opportunities.partners": "साझेदारहरूको लागि",
        "opportunities.partners.desc": "हामीसँग सहयोग गर्नुहोस्",
        "opportunities.enter": "प्रवेश गर्नुहोस् →",

        // Location
        "location.label": "स्थान",
        "location.title": "हामी कहाँ छौं",
        "location.subtitle": "६ माईल र ताकदाह बीचमा। पहाडमा लुकेको रत्न।",
        "location.satellite": "उपग्रह दृश्य",
        "location.houses": "जंगलमा बसेका २२ घरहरू",
        "location.maps": "Google Maps मा खोल्नुहोस् ↗",

        // Village Life
        "life.quote": "राम्रो खाना। इमानदार आतिथ्य। हाँसो र न्यानोपन। आफ्नो महसुस।",
        "life.attribution": "— आगन्तुकहरूले यहाँ अनुभव गर्ने कुरा",

        // Gaps
        "gaps.label": "लगानीकर्ताहरूको लागि",
        "gaps.title": "अवसरको खाडल",
        "gaps.subtitle": "उच्च माग। शून्य आपूर्ति। लगानीको लागि आदर्श।",
        "gaps.homestay": "होमस्टे",
        "gaps.cafe": "क्याफे",
        "gaps.guide": "गाइड",
        "gaps.organic": "जैविक खेती",
        "gaps.status": "खाडल",
        "gaps.potential": "होमस्टे सम्भावना: हिमाल दृश्य, प्रामाणिक अनुभव",

        // Economy
        "economy.label": "सक्रिय अर्थतन्त्र",
        "economy.title": "हामी के गर्छौं",
        "economy.subtitle": "खाना पकाउनेदेखि कोडिङसम्म। काम गर्ने गाउँले अर्थतन्त्र।",
        "economy.view": "सबै सेवाहरू हेर्नुहोस्",
        "economy.food": "खाना र आतिथ्य",
        "economy.agriculture": "कृषि",
        "economy.construction": "निर्माण",
        "economy.digital": "डिजिटल सेवाहरू",
        "economy.active": "सक्रिय",

        // Vision
        "vision.label": "दृष्टिकोण",
        "vision.title": "हामी के बनाउँदैछौं",
        "vision.portal": "गाउँ पोर्टल",
        "vision.portal.desc": "सबै सेवाहरूको लागि एक प्लेटफर्म",
        "vision.hub": "पर्यटन हब",
        "vision.hub.desc": "पहाडहरू बीचको गन्तव्य",
        "vision.network": "सीप नेटवर्क",
        "vision.network.desc": "प्रतिभाले अवसर भेट्छ",
        "vision.quote": "हामी पहुँचको लागि कुर्दैनौं। हामी पहिले अर्थतन्त्र बनाउँदैछौं।",

        // CTA
        "cta.title": "कथाको अंश बन्न तयार हुनुहुन्छ?",
        "cta.partner": "हामीसँग साझेदारी गर्नुहोस्",
        "cta.story": "हाम्रो कथा पढ्नुहोस्",

        // Footer
        "footer.tagline": "लामाहट्टा, दार्जीलिङको सानो गाउँको जीवित अभिलेख। २२ घर। ~९३ मानिस। एक कथा।",
        "footer.navigate": "नेभिगेट",
        "footer.connected": "जोडिइ रहनुहोस्",
        "footer.connected.desc": "स्थानीय अपडेट, सरकारी योजना, अवसरहरू।",
        "footer.subscribe": "अपडेटहरूमा सदस्यता लिनुहोस् →",
        "footer.credit": "जीवित अभिलेख · सुनरे गाउन, लामाहट्टा, दार्जीलिङ",
        "footer.unfinished": "यो साइट समाप्त भएको छैन। गाउँ पनि छैन।",
    },

    HI: {
        "nav.home": "होम",
        "nav.why": "यह क्यों मौजूद है",
        "nav.change": "बदलाव",
        "nav.economy": "हम क्या करते हैं",
        "nav.challenges": "चुनौतियाँ",
        "nav.voices": "आवाज़ें",
        "nav.partners": "भागीदार",
        "nav.updates": "अपडेट",
        "hero.location": "लामाहट्टा · दार्जीलिंग",
        "hero.title": "सुनरे गाउन",
        "hero.subtitle": "संक्रमण में एक गाँव की अर्थव्यवस्था",
        "hero.houses": "घर",
        "hero.residents": "निवासी",
        "hero.potential": "संभावना",
        "hero.scroll": "नीचे स्क्रॉल करें ↓",
        "hero.opportunity": "अवसर देखें",
        "hero.story": "हमारी कहानी",
        "opportunities.title": "अवसर",
        "opportunities.villagers": "ग्रामीणों के लिए",
        "opportunities.villagers.desc": "सेवाएं, योजनाएं और अवसर प्राप्त करें",
        "opportunities.investors": "निवेशकों के लिए",
        "opportunities.investors.desc": "अवसर की खाई देखें",
        "opportunities.partners": "भागीदारों के लिए",
        "opportunities.partners.desc": "हमारे साथ सहयोग करें",
        "opportunities.enter": "प्रवेश →",
        "location.label": "स्थान",
        "location.title": "हम कहाँ हैं",
        "location.subtitle": "6वें माइल और ताकदाह के बीच। पहाड़ों में छिपा हुआ रत्न।",
        "location.satellite": "उपग्रह दृश्य",
        "location.houses": "जंगल में बसे 22 घर",
        "location.maps": "Google Maps में खोलें ↗",
        "life.quote": "अच्छा खाना। ईमानदार मेहमाननवाज़ी। हास्य और गर्मजोशी। अपनापन।",
        "life.attribution": "— आगंतुक यहाँ क्या अनुभव करते हैं",
        "gaps.label": "निवेशकों के लिए",
        "gaps.title": "अवसर की खाई",
        "gaps.subtitle": "उच्च मांग। शून्य आपूर्ति। निवेश के लिए आदर्श।",
        "gaps.homestay": "होमस्टे",
        "gaps.cafe": "कैफे",
        "gaps.guide": "गाइड",
        "gaps.organic": "जैविक खेती",
        "gaps.status": "खाई",
        "gaps.potential": "होमस्टे क्षमता: पहाड़ी दृश्य, प्रामाणिक अनुभव",
        "economy.label": "सक्रिय अर्थव्यवस्था",
        "economy.title": "हम क्या करते हैं",
        "economy.subtitle": "खाना बनाने से कोडिंग तक। एक कामकाजी गाँव अर्थव्यवस्था।",
        "economy.view": "सभी सेवाएं देखें",
        "economy.food": "खाना और मेहमाननवाज़ी",
        "economy.agriculture": "कृषि",
        "economy.construction": "निर्माण",
        "economy.digital": "डिजिटल सेवाएं",
        "economy.active": "सक्रिय",
        "vision.label": "दृष्टि",
        "vision.title": "हम क्या बना रहे हैं",
        "vision.portal": "गाँव पोर्टल",
        "vision.portal.desc": "सभी सेवाओं के लिए एक प्लेटफॉर्म",
        "vision.hub": "पर्यटन हब",
        "vision.hub.desc": "पहाड़ियों के बीच गंतव्य",
        "vision.network": "कौशल नेटवर्क",
        "vision.network.desc": "प्रतिभा अवसर से मिलती है",
        "vision.quote": "हम पहुँच का इंतज़ार नहीं कर रहे। हम पहले अर्थव्यवस्था बना रहे हैं।",
        "cta.title": "कहानी का हिस्सा बनने के लिए तैयार?",
        "cta.partner": "हमारे साथ भागीदारी करें",
        "cta.story": "हमारी कहानी पढ़ें",
        "footer.tagline": "लामाहट्टा, दार्जीलिंग के एक छोटे गाँव का जीवित रिकॉर्ड। 22 घर। ~93 लोग। एक कहानी।",
        "footer.navigate": "नेविगेट",
        "footer.connected": "जुड़े रहें",
        "footer.connected.desc": "स्थानीय अपडेट, सरकारी योजनाएं, अवसर।",
        "footer.subscribe": "अपडेट के लिए सदस्यता लें →",
        "footer.credit": "जीवित रिकॉर्ड · सुनरे गाउन, लामाहट्टा, दार्जीलिंग",
        "footer.unfinished": "यह साइट पूरी नहीं हुई है। न ही गाँव।",
    },

    BN: {
        "nav.home": "হোম",
        "nav.why": "এটি কেন বিদ্যমান",
        "nav.change": "পরিবর্তন",
        "nav.economy": "আমরা কী করি",
        "nav.challenges": "চ্যালেঞ্জ",
        "nav.voices": "কণ্ঠস্বর",
        "nav.partners": "অংশীদার",
        "nav.updates": "আপডেট",
        "hero.location": "লামাহাট্টা · দার্জিলিং",
        "hero.title": "সুনরে গাউন",
        "hero.subtitle": "রূপান্তরে একটি গ্রাম অর্থনীতি",
        "hero.houses": "বাড়ি",
        "hero.residents": "বাসিন্দা",
        "hero.potential": "সম্ভাবনা",
        "hero.scroll": "নিচে স্ক্রোল করুন ↓",
        "hero.opportunity": "সুযোগ দেখুন",
        "hero.story": "আমাদের গল্প",
        "opportunities.title": "সুযোগ",
        "opportunities.villagers": "গ্রামবাসীদের জন্য",
        "opportunities.villagers.desc": "পরিষেবা, স্কিম এবং সুযোগ অ্যাক্সেস করুন",
        "opportunities.investors": "বিনিয়োগকারীদের জন্য",
        "opportunities.investors.desc": "সুযোগের ফাঁক দেখুন",
        "opportunities.partners": "অংশীদারদের জন্য",
        "opportunities.partners.desc": "আমাদের সাথে সহযোগিতা করুন",
        "opportunities.enter": "প্রবেশ করুন →",
        "location.label": "অবস্থান",
        "location.title": "আমরা কোথায় আছি",
        "location.subtitle": "৬ষ্ঠ মাইল এবং তাকদাহের মধ্যে। পাহাড়ে লুকানো রত্ন।",
        "location.satellite": "স্যাটেলাইট ভিউ",
        "location.houses": "বনের মধ্যে ২২টি বাড়ি",
        "location.maps": "Google Maps এ খুলুন ↗",
        "life.quote": "ভালো খাবার। সৎ আতিথেয়তা। হাস্যরস এবং উষ্ণতা। আপনত্বের অনুভূতি।",
        "life.attribution": "— দর্শনার্থীরা এখানে যা অনুভব করেন",
        "gaps.label": "বিনিয়োগকারীদের জন্য",
        "gaps.title": "সুযোগের ফাঁক",
        "gaps.subtitle": "উচ্চ চাহিদা। শূন্য সরবরাহ। বিনিয়োগের জন্য আদর্শ।",
        "gaps.homestay": "হোমস্টে",
        "gaps.cafe": "ক্যাফে",
        "gaps.guide": "গাইড",
        "gaps.organic": "জৈব চাষ",
        "gaps.status": "ফাঁক",
        "gaps.potential": "হোমস্টে সম্ভাবনা: পাহাড়ের দৃশ্য, প্রামাণিক অভিজ্ঞতা",
        "economy.label": "সক্রিয় অর্থনীতি",
        "economy.title": "আমরা কী করি",
        "economy.subtitle": "রান্না থেকে কোডিং পর্যন্ত। একটি কর্মক্ষম গ্রাম অর্থনীতি।",
        "economy.view": "সব পরিষেবা দেখুন",
        "economy.food": "খাবার ও আতিথেয়তা",
        "economy.agriculture": "কৃষি",
        "economy.construction": "নির্মাণ",
        "economy.digital": "ডিজিটাল পরিষেবা",
        "economy.active": "সক্রিয়",
        "vision.label": "দৃষ্টি",
        "vision.title": "আমরা কী বানাচ্ছি",
        "vision.portal": "গ্রাম পোর্টাল",
        "vision.portal.desc": "সব পরিষেবার জন্য এক প্ল্যাটফর্ম",
        "vision.hub": "পর্যটন হাব",
        "vision.hub.desc": "পাহাড়ের মধ্যে গন্তব্য",
        "vision.network": "দক্ষতা নেটওয়ার্ক",
        "vision.network.desc": "প্রতিভা সুযোগের সাথে মিলিত হয়",
        "vision.quote": "আমরা অ্যাক্সেসের জন্য অপেক্ষা করছি না। আমরা প্রথমে অর্থনীতি তৈরি করছি।",
        "cta.title": "গল্পের অংশ হতে প্রস্তুত?",
        "cta.partner": "আমাদের সাথে অংশীদার হন",
        "cta.story": "আমাদের গল্প পড়ুন",
        "footer.tagline": "লামাহাট্টা, দার্জিলিংয়ের একটি ছোট গ্রামের জীবন্ত রেকর্ড। ২২টি বাড়ি। ~৯৩ জন। একটি গল্প।",
        "footer.navigate": "নেভিগেট",
        "footer.connected": "সংযুক্ত থাকুন",
        "footer.connected.desc": "স্থানীয় আপডেট, সরকারি স্কিম, সুযোগ।",
        "footer.subscribe": "আপডেটের জন্য সাবস্ক্রাইব করুন →",
        "footer.credit": "জীবন্ত রেকর্ড · সুনরে গাউন, লামাহাট্টা, দার্জিলিং",
        "footer.unfinished": "এই সাইট শেষ হয়নি। গ্রামও না।",
    },

    DZ: {
        // Bhutanese/Dzongkha
        "nav.home": "མདུན་ཤོག",
        "nav.why": "འདི་ག་ཅི་སྦེ་ཡོདཔ",
        "nav.change": "བསྒྱུར་བཅོས",
        "nav.economy": "ང་བཅས་ག་ཅི་འབདཝ",
        "nav.challenges": "དཀའ་ངལ",
        "nav.voices": "སྐད་སྒྲ",
        "nav.partners": "མཉམ་འབྲེལ",
        "nav.updates": "གསར་བཏོན",
        "hero.location": "ལ་མ་ཧཊྭཱ · དར་ཇི་གླིང",
        "hero.title": "Sunaray Gown",
        "hero.subtitle": "གྱུར་བའི་གཡུས་ཚན་དཔལ་འབྱོར",
        "hero.houses": "ཁྱིམ",
        "hero.residents": "མི་སེར",
        "hero.potential": "ནུས་པ",
        "hero.scroll": "མར་བཤུད ↓",
        "hero.opportunity": "གོ་སྐབས་བལྟ",
        "hero.story": "ང་བཅས་ཀྱི་ལོ་རྒྱུས",
        "opportunities.title": "གོ་སྐབས",
        "opportunities.villagers": "གཡུས་མིའི་དོན་ལུ",
        "opportunities.villagers.desc": "ཞབས་ཏོག་དང་གོ་སྐབས་ལེན",
        "opportunities.investors": "མ་རྩ་བཙུགས་མི་དོན་ལུ",
        "opportunities.investors.desc": "གོ་སྐབས་ཀྱི་སྟོངམ་བལྟ",
        "opportunities.partners": "མཉམ་འབྲེལ་པའི་དོན་ལུ",
        "opportunities.partners.desc": "ང་བཅས་དང་མཉམ་འབྲེལ་འབད",
        "opportunities.enter": "ནང་འཛུལ →",
        "location.label": "ས་གནས",
        "location.title": "ང་བཅས་ག་ཏེ་ཡོད",
        "location.subtitle": "མའི་ལི་དྲུག་པ་དང་ཏཀ་དྷ་བར་ན། རི་ནང་གི་རིན་ཐང་ཅན།",
        "location.satellite": "མཁའ་དབྱིངས་མཐོང་ཚད",
        "location.houses": "ནགས་ནང་གི་ཁྱིམ་ཉི་ཤུ་རྩ་གཉིས",
        "location.maps": "Google Maps ནང་ཁ་ཕྱེ ↗",
        "life.quote": "བཟའ་ནོར་ལེགས། བསྟུན་འགྲིགས་བདེནམ། གད་མོ་དང་དྲོ་བ། རང་ཁྱིམ་འདྲ།",
        "life.attribution": "— འགྱོ་མི་གིས་ནཱ་མྱོང་བ",
        "vision.quote": "ང་བཅས་འབྱོར་ལམ་བསྒུགས་མིན་འདུག། ང་བཅས་ཧེ་མ་དཔལ་འབྱོར་བཟོ་དོ།",
        "cta.title": "ལོ་རྒྱུས་ཀྱི་ཆ་ཤས་འགྱོ་ནིའི་གྲ་སྒྲིག་ཡོད?",
        "cta.partner": "ང་བཅས་དང་མཉམ་འབྲེལ་འབད",
        "cta.story": "ང་བཅས་ཀྱི་ལོ་རྒྱུས་ལྷག",
    },

    TB: {
        // Tibetan
        "nav.home": "མདུན་ཤོག",
        "nav.why": "འདི་ག་རེ་ཡིན",
        "nav.change": "འགྱུར་བ",
        "nav.economy": "ང་ཚོ་གང་བྱེད",
        "nav.challenges": "དཀའ་ངལ",
        "nav.voices": "སྐད་སྒྲ",
        "nav.partners": "མཉམ་འབྲེལ་བ",
        "nav.updates": "གསར་གཏོད",
        "hero.location": "ལ་མ་ཧཊྭཱ · དར་རྒྱས་གླིང",
        "hero.title": "Sunaray Gown",
        "hero.subtitle": "འགྱུར་བཞིན་པའི་གྲོང་གསེབ་དཔལ་འབྱོར",
        "hero.houses": "ཁང་པ",
        "hero.residents": "མི་སེར",
        "hero.potential": "ནུས་པ",
        "hero.scroll": "མར་འཁྱེར ↓",
        "hero.opportunity": "གོ་སྐབས་ལྟ",
        "hero.story": "ང་ཚོའི་ལོ་རྒྱུས",
        "opportunities.title": "གོ་སྐབས",
        "opportunities.villagers": "གྲོང་མིའི་ཆེད",
        "opportunities.villagers.desc": "ཞབས་ཞུ་དང་གོ་སྐབས་ལེན",
        "opportunities.investors": "མ་རྩ་འཇོག་མཁན་ཆེད",
        "opportunities.investors.desc": "གོ་སྐབས་བར་སྟོང་ལྟ",
        "opportunities.partners": "མཉམ་ལས་པའི་ཆེད",
        "opportunities.partners.desc": "ང་ཚོ་དང་མཉམ་ལས་བྱོས",
        "opportunities.enter": "འཛུལ →",
        "location.label": "ས་གནས",
        "location.title": "ང་ཚོ་གང་དུ་ཡོད",
        "location.subtitle": "དྲུག་པ་མའིལ་དང་ཏཀ་དྷ་བར། རི་ཁྲོད་ཀྱི་རིན་ཐང་ཆེན།",
        "vision.quote": "ང་ཚོ་ལྷན་ལམ་སྒུག་གི་མིན། ང་ཚོ་སྔོན་ལ་དཔལ་འབྱོར་བཟོ་གི་ཡོད།",
        "cta.title": "ལོ་རྒྱུས་ཀྱི་ཆ་ཤས་བྱེད་འདོད་ཡོད་དམ?",
        "cta.partner": "ང་ཚོ་དང་མཉམ་འབྲེལ་བྱོས",
        "cta.story": "ང་ཚོའི་ལོ་རྒྱུས་ཀློག",
    },

    SH: {
        // Sherpa
        "nav.home": "Tse-khang",
        "nav.why": "Di garé yin",
        "nav.change": "Gyur-wa",
        "nav.economy": "Nga-tsö ka jé",
        "nav.challenges": "Kang-ngal",
        "nav.voices": "Ké-dra",
        "nav.partners": "Nyam-drel-wa",
        "nav.updates": "Sar-tön",
        "hero.location": "Lama-hatta · Darjeeling",
        "hero.title": "Sunaray Gown",
        "hero.subtitle": "Gyur-zhin-pé Yul-chung Pal-jor",
        "hero.houses": "Khangpa",
        "hero.residents": "Mi-ser",
        "hero.potential": "Nü-pa",
        "hero.scroll": "Marla teng ↓",
        "hero.opportunity": "Go-kab ta",
        "hero.story": "Nga-tsö Lo-gyü",
        "opportunities.title": "Go-kab",
        "opportunities.villagers": "Yul-mi ché",
        "opportunities.villagers.desc": "Zhab-zhü dang go-kab len",
        "opportunities.investors": "Ma-tsa jog-khen ché",
        "opportunities.investors.desc": "Go-kab bar-tong ta",
        "opportunities.partners": "Nyam-lé-pa ché",
        "opportunities.partners.desc": "Nga-tsö dang nyam-lé jö",
        "opportunities.enter": "Dzü →",
        "location.label": "Sa-né",
        "location.title": "Nga-tsö gang-du yö",
        "location.subtitle": "6th Mile dang Takdah bar. Ri-khé rin-thang chen.",
        "vision.quote": "Nga-tsö thon-lam gü-gi min. Nga-tsö ngön-la pal-jor zo-gi yö.",
        "cta.title": "Lo-gyü cha-shé jé-dö yö-pe?",
        "cta.partner": "Nga-tsö dang nyam-drel jö",
        "cta.story": "Nga-tsö lo-gyü log",
    },

    ZH: {
        // Chinese
        "nav.home": "首页",
        "nav.why": "为什么存在",
        "nav.change": "变化",
        "nav.economy": "我们做什么",
        "nav.challenges": "挑战",
        "nav.voices": "声音",
        "nav.partners": "合作伙伴",
        "nav.updates": "更新",
        "hero.location": "拉马哈塔 · 大吉岭",
        "hero.title": "Sunaray Gown",
        "hero.subtitle": "转型中的乡村经济",
        "hero.houses": "房屋",
        "hero.residents": "居民",
        "hero.potential": "潜力",
        "hero.scroll": "向下滚动 ↓",
        "hero.opportunity": "查看机会",
        "hero.story": "我们的故事",
        "opportunities.title": "机会",
        "opportunities.villagers": "村民专区",
        "opportunities.villagers.desc": "获取服务、计划和机会",
        "opportunities.investors": "投资者专区",
        "opportunities.investors.desc": "查看机会缺口",
        "opportunities.partners": "合作伙伴专区",
        "opportunities.partners.desc": "与我们合作",
        "opportunities.enter": "进入 →",
        "location.label": "位置",
        "location.title": "我们在哪里",
        "location.subtitle": "位于6英里和塔克达之间。山间隐藏的宝石。",
        "location.satellite": "卫星视图",
        "location.houses": "森林中的22栋房屋",
        "location.maps": "在Google Maps中打开 ↗",
        "life.quote": "美食。诚挚的热情款待。幽默与温暖。归属感。",
        "life.attribution": "— 游客在这里的体验",
        "gaps.label": "投资者专区",
        "gaps.title": "机会缺口",
        "gaps.subtitle": "高需求。零供应。投资的理想选择。",
        "gaps.homestay": "民宿",
        "gaps.cafe": "咖啡馆",
        "gaps.guide": "导游",
        "gaps.organic": "有机农场",
        "gaps.status": "缺口",
        "gaps.potential": "民宿潜力：山景，真实体验",
        "economy.label": "活跃经济",
        "economy.title": "我们做什么",
        "economy.subtitle": "从烹饪到编程。一个运转中的乡村经济。",
        "economy.view": "查看所有服务",
        "economy.food": "餐饮与款待",
        "economy.agriculture": "农业",
        "economy.construction": "建筑",
        "economy.digital": "数字服务",
        "economy.active": "活跃",
        "vision.label": "愿景",
        "vision.title": "我们正在建设什么",
        "vision.portal": "村庄门户",
        "vision.portal.desc": "所有服务的统一平台",
        "vision.hub": "旅游中心",
        "vision.hub.desc": "山间的目的地",
        "vision.network": "技能网络",
        "vision.network.desc": "人才遇见机会",
        "vision.quote": "我们不等待接入。我们先建设经济。",
        "cta.title": "准备好成为故事的一部分了吗？",
        "cta.partner": "与我们合作",
        "cta.story": "阅读我们的故事",
        "footer.tagline": "大吉岭拉马哈塔一个小村庄的生活记录。22栋房屋。约93人。一个故事。",
        "footer.navigate": "导航",
        "footer.connected": "保持联系",
        "footer.connected.desc": "本地更新、政府计划、机会。",
        "footer.subscribe": "订阅更新 →",
        "footer.credit": "生活记录 · Sunaray Gown, 拉马哈塔, 大吉岭",
        "footer.unfinished": "这个网站尚未完成。村庄也是。",
    },

    TH: {
        // Thai
        "nav.home": "หน้าแรก",
        "nav.why": "ทำไมถึงมีอยู่",
        "nav.change": "การเปลี่ยนแปลง",
        "nav.economy": "เราทำอะไร",
        "nav.challenges": "ความท้าทาย",
        "nav.voices": "เสียง",
        "nav.partners": "พันธมิตร",
        "nav.updates": "อัปเดต",
        "hero.location": "ลามาฮัตตา · ดาร์จีลิ่ง",
        "hero.title": "Sunaray Gown",
        "hero.subtitle": "เศรษฐกิจหมู่บ้านที่กำลังเปลี่ยนแปลง",
        "hero.houses": "บ้าน",
        "hero.residents": "ผู้อยู่อาศัย",
        "hero.potential": "ศักยภาพ",
        "hero.scroll": "เลื่อนลง ↓",
        "hero.opportunity": "ดูโอกาส",
        "hero.story": "เรื่องราวของเรา",
        "opportunities.title": "โอกาส",
        "opportunities.villagers": "สำหรับชาวบ้าน",
        "opportunities.villagers.desc": "เข้าถึงบริการ โครงการ และโอกาส",
        "opportunities.investors": "สำหรับนักลงทุน",
        "opportunities.investors.desc": "ดูช่องว่างโอกาส",
        "opportunities.partners": "สำหรับพันธมิตร",
        "opportunities.partners.desc": "ร่วมมือกับเรา",
        "opportunities.enter": "เข้าสู่ →",
        "location.label": "ที่ตั้ง",
        "location.title": "เราอยู่ที่ไหน",
        "location.subtitle": "ระหว่างไมล์ที่ 6 และทักดาห์ อัญมณีที่ซ่อนอยู่ในภูเขา",
        "location.satellite": "มุมมองดาวเทียม",
        "location.houses": "22 หลังคาเรือนในป่า",
        "location.maps": "เปิดใน Google Maps ↗",
        "life.quote": "อาหารอร่อย การต้อนรับที่จริงใจ อารมณ์ขันและความอบอุ่น ความรู้สึกเป็นส่วนหนึ่ง",
        "life.attribution": "— สิ่งที่ผู้มาเยือนสัมผัสได้ที่นี่",
        "vision.quote": "เราไม่รอการเข้าถึง เราสร้างเศรษฐกิจก่อน",
        "cta.title": "พร้อมที่จะเป็นส่วนหนึ่งของเรื่องราวแล้วหรือยัง?",
        "cta.partner": "ร่วมเป็นพันธมิตรกับเรา",
        "cta.story": "อ่านเรื่องราวของเรา",
        "footer.tagline": "บันทึกชีวิตของหมู่บ้านเล็กๆ ในลามาฮัตตา ดาร์จีลิ่ง 22 บ้าน ~93 คน หนึ่งเรื่องราว",
        "footer.navigate": "นำทาง",
        "footer.connected": "เชื่อมต่อ",
        "footer.connected.desc": "อัปเดตท้องถิ่น โครงการรัฐบาล โอกาส",
        "footer.subscribe": "สมัครรับการอัปเดต →",
        "footer.credit": "บันทึกชีวิต · Sunaray Gown, Lamahatta, Darjeeling",
        "footer.unfinished": "เว็บไซต์นี้ยังไม่เสร็จ หมู่บ้านก็เช่นกัน",
    },

    FR: {
        // French
        "nav.home": "Accueil",
        "nav.why": "Pourquoi ça existe",
        "nav.change": "Changement",
        "nav.economy": "Ce que nous faisons",
        "nav.challenges": "Défis",
        "nav.voices": "Voix",
        "nav.partners": "Partenaires",
        "nav.updates": "Mises à jour",
        "hero.location": "Lamahatta · Darjeeling",
        "hero.title": "Sunaray Gown",
        "hero.subtitle": "Une économie villageoise en transition",
        "hero.houses": "Maisons",
        "hero.residents": "Résidents",
        "hero.potential": "Potentiel",
        "hero.scroll": "Défiler pour explorer ↓",
        "hero.opportunity": "Voir l'opportunité",
        "hero.story": "Notre histoire",
        "opportunities.title": "Opportunités",
        "opportunities.villagers": "Pour les villageois",
        "opportunities.villagers.desc": "Accédez aux services, programmes et opportunités",
        "opportunities.investors": "Pour les investisseurs",
        "opportunities.investors.desc": "Voir les opportunités manquantes",
        "opportunities.partners": "Pour les partenaires",
        "opportunities.partners.desc": "Collaborez avec nous",
        "opportunities.enter": "Entrer →",
        "location.label": "Emplacement",
        "location.title": "Où nous sommes",
        "location.subtitle": "Entre 6th Mile et Takdah. Un joyau caché dans les collines.",
        "location.satellite": "Vue satellite",
        "location.houses": "22 maisons nichées dans la forêt",
        "location.maps": "Ouvrir dans Google Maps ↗",
        "life.quote": "Bonne nourriture. Hospitalité honnête. Humour et chaleur. Un sentiment d'appartenance.",
        "life.attribution": "— Ce que les visiteurs vivent ici",
        "gaps.label": "Pour les investisseurs",
        "gaps.title": "Opportunités manquantes",
        "gaps.subtitle": "Forte demande. Aucune offre. Idéal pour l'investissement.",
        "gaps.homestay": "Hébergement",
        "gaps.cafe": "Café",
        "gaps.guide": "Guide",
        "gaps.organic": "Ferme bio",
        "gaps.status": "Manque",
        "gaps.potential": "Potentiel d'hébergement: Vue montagne, expérience authentique",
        "economy.label": "Économie active",
        "economy.title": "Ce que nous faisons",
        "economy.subtitle": "De la cuisine au codage. Une économie villageoise fonctionnelle.",
        "economy.view": "Voir tous les services",
        "economy.food": "Alimentation & Hospitalité",
        "economy.agriculture": "Agriculture",
        "economy.construction": "Construction",
        "economy.digital": "Services numériques",
        "economy.active": "actif",
        "vision.label": "La vision",
        "vision.title": "Ce que nous construisons",
        "vision.portal": "Portail du village",
        "vision.portal.desc": "Une plateforme pour tous les services",
        "vision.hub": "Hub touristique",
        "vision.hub.desc": "Destination entre les collines",
        "vision.network": "Réseau de compétences",
        "vision.network.desc": "Le talent rencontre l'opportunité",
        "vision.quote": "Nous n'attendons pas l'accès. Nous construisons d'abord une économie.",
        "cta.title": "Prêt à faire partie de l'histoire ?",
        "cta.partner": "Devenez partenaire",
        "cta.story": "Lire notre histoire",
        "footer.tagline": "Un document vivant d'un petit village à Lamahatta, Darjeeling. 22 maisons. ~93 personnes. Une histoire.",
        "footer.navigate": "Naviguer",
        "footer.connected": "Rester connecté",
        "footer.connected.desc": "Actualités locales, programmes gouvernementaux, opportunités.",
        "footer.subscribe": "S'abonner aux mises à jour →",
        "footer.credit": "Document vivant · Sunaray Gown, Lamahatta, Darjeeling",
        "footer.unfinished": "Ce site n'est pas fini. Le village non plus.",
    },
};

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
    const [language, setLanguage] = useState<Language>("EN");

    const t = (key: string): string => {
        return translations[language]?.[key] || translations["EN"]?.[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};
