"use client";

import React, { createContext, useContext, useState } from "react";

export type Language = "EN" | "NE" | "HI" | "BN" | "DZ" | "TB" | "SH" | "ZH" | "TH" | "FR";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
};

// Comprehensive translations for all site content
const translations: Record<Language, Record<string, string>> = {
    EN: {
        // Navigation
        "nav.home": "Home",
        "nav.why": "Story",
        "nav.change": "Change",
        "nav.economy": "Opportunity",
        "nav.challenges": "Challenges",
        "nav.voices": "Voices",
        "nav.village": "Talent",
        "nav.hub": "Hub",
        "nav.partners": "Partners",
        "nav.updates": "Updates",

        // Hero Section
        "hero.location": "Lamahatta · Darjeeling",
        "hero.title": "Seemana Gaon",
        "hero.subtitle": "A village economy in transition",
        "hero.houses": "Houses",
        "hero.residents": "Residents",
        "hero.potential": "Potential",
        "hero.scroll": "Scroll to explore ↓",
        "hero.opportunity": "See the Opportunity",
        "hero.story": "Our Story",
        "hero.join": "Join the Village",
        "hero.panorama.title": "A Wide Horizon",
        "hero.panorama.desc": "Every corner of Seemana Gaon is connected by a shared history and breathtaking views of the surrounding mountains.",
        "hero.main_title": "Sunaray Gaon is not just a village website.",
        "hero.main_subtitle": "It is the front door to a living village economy.",

        // Opportunities Section
        "opportunities.empty": "No opportunities listed yet.",
        "opportunities.add": "Add Opportunity",
        "opportunities.desc": "List jobs, training, contracts, and business needs.",

        // Voices Page
        "voices.label": "Voices page",
        "voices.title": "This page should become the village opinion board.",
        "voices.subtitle": "People should be able to say what is needed, what is working, and what should be built next.",
        "voices.post_heading": "What should be posted here",
        "voices.desc": "This page should not be decorative. It should become the place where the village speaks in categories that help action happen.",
        "voices.topic": "Topic",
        "voices.quote": "If the village cannot state its needs clearly, other people will define them badly.",
        "voices.cta.updates": "Go to community updates",
        "voices.cta.hub": "Enter the hub",
        "opportunities.villagers": "For Villagers",
        "opportunities.villagers.desc": "Access services, schemes & opportunities",
        "opportunities.investors": "For Investors",
        "opportunities.investors.desc": "See the opportunity gaps",
        "opportunities.partners": "For Partners",
        "opportunities.partners.desc": "Collaborate with us",
        "opportunities.enter": "Enter →",

        // Location Section
        "location.label": "Location",
        "location.title": "Where We Are",
        "location.subtitle": "Between 6th Mile and Takdah. A hidden gem in the hills.",
        "location.satellite": "Satellite View",
        "location.houses": "22 Houses nestled in the forest",
        "location.maps": "Open in Google Maps ↗",

        // Village Life
        "life.quote": "Good food. Honest hospitality. Humor and warmth. A sense of belonging.",
        "life.attribution": "— What visitors experience here",

        // Opportunity Gaps
        "gaps.label": "For Investors",
        "gaps.title": "Opportunity Gaps",
        "gaps.subtitle": "High demand. Zero supply. Ideal for investment.",
        "gaps.homestay": "Homestay",
        "gaps.cafe": "Cafe",
        "gaps.guide": "Guide",
        "gaps.organic": "Organic Farm",
        "gaps.status": "Gap",
        "gaps.potential": "Homestay Potential: Mountain views, authentic experience",

        // Economy
        "economy.label": "Active Economy",
        "economy.title": "What We Do",
        "economy.subtitle": "From cooking to coding. A working village economy.",
        "economy.view": "View All Services",
        "economy.food": "Food & Hospitality",
        "economy.agriculture": "Agriculture",
        "economy.construction": "Construction",
        "economy.digital": "Digital Services",
        "economy.active": "active",

        // Vision
        "vision.label": "The Vision",
        "vision.title": "What We're Building",
        "vision.portal": "Village Portal",
        "vision.portal.desc": "One platform for all services",
        "vision.hub": "Tourism Hub",
        "vision.hub.desc": "Destination between hills",
        "vision.network": "Skills Network",
        "vision.network.desc": "Talent meets opportunity",
        "vision.quote": "We are not waiting for access. We are building an economy first.",

        // CTA
        "cta.title": "Ready to be part of the story?",
        "cta.partner": "Partner With Us",
        "cta.story": "Read Our Story",

        // Sunlight Hub
        "hub.title": "Sunlight Hub",
        "hub.subtitle": "Your community space. Share stories, celebrate wins, and stay connected with Seemana Gaon.",
        "hub.join": "Join the Community",
        "hub.explore": "Explore Spaces",
        "hub.explore.desc": "Find your corner of the village",
        "hub.enter": "Explore",
        "hub.creators": "Creators Corner",
        "hub.creators.desc": "Video makers, TikTokers & content creators showcasing village life",
        "hub.youth": "Young Voices",
        "hub.youth.desc": "Kids' artwork, school achievements & future talents of Sunaray",
        "hub.mothers": "Ama's Circle",
        "hub.mothers.desc": "Recipes, traditions & wisdom passed down through generations",
        "hub.fathers": "Bua's Guild",
        "hub.fathers.desc": "Construction, farming tips & mentorship from village builders",
        "hub.updates": "Development Notes",
        "hub.updates.desc": "Village announcements, schemes & community meetings",
        "hub.praises": "Praises & Pride",
        "hub.praises.desc": "Achievements, thank you notes & festival highlights",
        "hub.stats.members": "Members",
        "hub.stats.families": "Families",
        "hub.stats.stories": "Stories",

        // Personality Test
        "hub.personality": "Find My Personality",
        "hub.personality.desc": "Discover your true self with our village-style quiz!",
        "personality.title": "Village Personality Quiz",
        "personality.subtitle": "10 questions. Brutally honest results.",
        "personality.start": "Start Quiz",
        "personality.submit": "Reveal My True Self",
        "personality.retake": "Retake Quiz",

        // Footer
        "footer.tagline": "A living record of a small village in Lamahatta, Darjeeling. 22 houses. ~93 people. One story.",
        "footer.navigate": "Navigate",
        "footer.connected": "Stay Connected",
        "footer.connected.desc": "Local updates, government schemes, opportunities.",
        "footer.subscribe": "Subscribe to Updates →",
        "footer.credit": "A Living Record · Seemana Gaon, Lamahatta, Darjeeling",
        "footer.unfinished": "This site is not finished. Neither is the village.",

        // Village Page
        "village.title": "The Village",
        "village.talent": "Talent",
        "village.subtitle": "Discover the creators, guides, and artisans that make Lamahatta special.",
        "village.noPortfolios": "No portfolios yet. Be the first!",
        "village.createPortfolio": "Create Your Portfolio",

        // Common
        "common.loading": "Loading...",
        "common.partnerWithUs": "Partner With Us",

        // Investor Section
        "investor.label": "For Investors",
        "investor.title": "A Letter to You",
        "investor.greeting": "Dear Investor,",
        "investor.p1": "If you are looking for land to build a vacation home, homestay, restaurant, or retreat in the mountains of Darjeeling — we welcome you to Sunaray Gown.",
        "investor.p2": "Our village sits at the edge of Lamahatta, surrounded by pine forests and mountain views. We have 22 houses, 93 residents, and a community that values careful growth over quick money.",
        "investor.p3": "We are open to partnerships that respect our land, involve our people, and contribute to the local economy. Whether you want to build a boutique homestay, a small café, or simply own a piece of mountain peace — let's talk.",
        "investor.closing": "We remember who stood with us when we were small.",
        "investor.formTitle": "Interested in Investing?",
        "investor.phone": "Phone Number",
        "investor.interest": "What are you interested in?",
        "investor.placeholder": "E.g., Building a homestay, buying land, opening a café...",
        "investor.submit": "Contact Us",
        "investor.sending": "Sending...",
        "investor.success": "Thank you! We'll be in touch soon.",
        "investor.error": "Something went wrong. Please try again.",
        "investor.learn": "Learn More About Partnerships →",

        // Partners Page
        "partners.label": "Invest & Collaborate",
        "partners.title": "Work With Us",
        "partners.subtitle": "We are valuable because we serve genuinely, grow carefully, and remember.",
        "partners.genuine": "Genuine Service",
        "partners.genuine.desc": "We serve our community first",
        "partners.pride": "Local Pride",
        "partners.pride.desc": "We take pride in our work",
        "partners.growth": "Careful Growth",
        "partners.growth.desc": "We grow without losing identity",
        "partners.memory": "Long Memory",
        "partners.memory.desc": "We remember who stood with us",
        "partners.experience": "People who come here experience:",
        "partners.quote": "We do not sell spectacle. We build trust.",
        "partners.formTitle": "Interested in partnering?",
        "partners.formDesc": "Reach out for investment opportunities, collaborations, or visits.",
        "partners.phone": "Phone Number",
        "partners.message": "Message (optional)",
        "partners.messagePlaceholder": "Tell us how you'd like to collaborate...",
        "partners.submit": "Get In Touch",
        "partners.success": "Thank you! We'll get back to you soon.",

        // Dashboard
        "dashboard.loading": "Loading...",
        "dashboard.title": "Member Dashboard",
        "dashboard.adminTitle": "Admin Dashboard",
        "dashboard.welcome": "Welcome back",
        "dashboard.signOut": "Sign Out",
        "dashboard.role.villager": "Role: Worker / Villager",
        "dashboard.role.admin": "Role: Samaj Head / Admin",
        "dashboard.editPortfolio": "Edit Your Portfolio",
        "dashboard.previewTips": "Preview & Tips",
        "dashboard.tipsDesc": "Your portfolio helps visitors discover your talents. Make sure to:",
        "dashboard.tip1": "Choose a clear title (e.g., 'Homestay & Local Guide').",
        "dashboard.tip2": "Write a short but engaging bio.",
        "dashboard.tip3": "List your key skills or offerings.",
        "dashboard.tip4": "Update your contact info so people can reach you.",
        "dashboard.admin.pending": "Pending Approvals",
        "dashboard.admin.pendingDesc": "Review updates from villagers.",
        "dashboard.admin.noPending": "No pending items right now.",
        "dashboard.admin.users": "Manage Users",
        "dashboard.admin.usersDesc": "View registered villagers.",
        "dashboard.admin.inquiries": "Investor Inquiries",
        "dashboard.admin.inquiriesDesc": "Review partnership requests."
    },

    NE: {
        // Navigation
        "nav.home": "गृहपृष्ठ",
        "nav.why": "कथा",
        "nav.change": "परिवर्तन",
        "nav.economy": "अवसर",
        "nav.challenges": "चुनौतीहरू",
        "nav.voices": "आवाजहरू",
        "nav.village": "प्रतिभा",
        "nav.hub": "हब",
        "nav.partners": "साझेदारहरू",
        "nav.updates": "अपडेटहरू",

        // Hero
        "hero.location": "लामाहट्टा · दार्जीलिङ",
        "hero.title": "सुनरे गाउन",
        "hero.subtitle": "संक्रमणमा रहेको गाउँले अर्थतन्त्र",
        "hero.houses": "घरहरू",
        "hero.residents": "बासिन्दाहरू",
        "hero.potential": "सम्भावना",
        "hero.scroll": "तल स्क्रोल गर्नुहोस् ↓",
        "hero.opportunity": "अवसर हेर्नुहोस्",
        "hero.story": "हाम्रो कथा",
        "hero.join": "गाउँमा सामेल हुनुहोस्",
        "hero.panorama.title": "फराकिलो क्षितिज",
        "hero.panorama.desc": "सीमा गाउँको हरेक कुना साझा इतिहास र वरपरका पहाडहरूको मनमोहक दृश्यले जोडिएको छ।",
        "hero.main_title": "सुनरे गाउँ केवल एउटा गाउँको वेबसाइट होइन।",
        "hero.main_subtitle": "यो एउटा जीवित गाउँले अर्थतन्त्रको मूल ढोका हो।",

        // Opportunities
        "opportunities.title": "अवसरहरू",
        "opportunities.villagers": "गाउँलेहरूको लागि",
        "opportunities.villagers.desc": "सेवा, योजना र अवसरहरू पहुँच गर्नुहोस्",
        "opportunities.investors": "लगानीकर्ताहरूको लागि",
        "opportunities.investors.desc": "अवसरको खाडल हेर्नुहोस्",
        "opportunities.partners": "साझेदारहरूको लागि",
        "opportunities.partners.desc": "हामीसँग सहयोग गर्नुहोस्",
        "opportunities.enter": "प्रवेश गर्नुहोस् →",

        // Location
        "location.label": "स्थान",
        "location.title": "हामी कहाँ छौं",
        "location.subtitle": "६ माईल र ताकदाह बीचमा। पहाडमा लुकेको रत्न।",
        "location.satellite": "उपग्रह दृश्य",
        "location.houses": "जंगलमा बसेका २२ घरहरू",
        "location.maps": "Google Maps मा खोल्नुहोस् ↗",

        // Village Life
        "life.quote": "राम्रो खाना। इमानदार आतिथ्य। हाँसो र न्यानोपन। आफ्नो महसुस।",
        "life.attribution": "— आगन्तुकहरूले यहाँ अनुभव गर्ने कुरा",

        // Gaps
        "gaps.label": "लगानीकर्ताहरूको लागि",
        "gaps.title": "अवसरको खाडल",
        "gaps.subtitle": "उच्च माग। शून्य आपूर्ति। लगानीको लागि आदर्श।",
        "gaps.homestay": "होमस्टे",
        "gaps.cafe": "क्याफे",
        "gaps.guide": "गाइड",
        "gaps.organic": "जैविक खेती",
        "gaps.status": "खाडल",
        "gaps.potential": "होमस्टे सम्भावना: हिमाल दृश्य, प्रामाणिक अनुभव",

        // Economy
        "economy.label": "सक्रिय अर्थतन्त्र",
        "economy.title": "हामी के गर्छौं",
        "economy.subtitle": "खाना पकाउनेदेखि कोडिङसम्म। काम गर्ने गाउँले अर्थतन्त्र।",
        "economy.view": "सबै सेवाहरू हेर्नुहोस्",
        "economy.food": "खाना र आतिथ्य",
        "economy.agriculture": "कृषि",
        "economy.construction": "निर्माण",
        "economy.digital": "डिजिटल सेवाहरू",
        "economy.active": "सक्रिय",

        // Vision
        "vision.label": "दृष्टिकोण",
        "vision.title": "हामी के बनाउँदैछौं",
        "vision.portal": "गाउँ पोर्टल",
        "vision.portal.desc": "सबै सेवाहरूको लागि एक प्लेटफर्म",
        "vision.hub": "पर्यटन हब",
        "vision.hub.desc": "पहाडहरू बीचको गन्तव्य",
        "vision.network": "सीप नेटवर्क",
        "vision.network.desc": "प्रतिभाले अवसर भेट्छ",
        "vision.quote": "हामी पहुँचको लागि कुर्दैनौं। हामी पहिले अर्थतन्त्र बनाउँदैछौं।",

        // CTA
        "cta.title": "कथाको अंश बन्न तयार हुनुहुन्छ?",
        "cta.partner": "हामीसँग साझेदारी गर्नुहोस्",
        "cta.story": "हाम्रो कथा पढ्नुहोस्",

        // Footer
        "footer.tagline": "लामाहट्टा, दार्जीलिङको सानो गाउँको जीवित अभिलेख। २२ घर। ~९३ मानिस। एक कथा।",
        "footer.navigate": "नेभिगेट",
        "footer.connected": "जोडिइ रहनुहोस्",
        "footer.connected.desc": "स्थानीय अपडेट, सरकारी योजना, अवसरहरू।",
        "footer.subscribe": "अपडेटहरूमा सदस्यता लिनुहोस् →",
        "footer.credit": "जीवित अभिलेख · सुनरे गाउन, लामाहट्टा, दार्जीलिङ",
        "footer.unfinished": "यो साइट समाप्त भएको छैन। गाउँ पनि छैन।",

        // Sunlight Hub
        "hub.title": "सनलाइट हब",
        "hub.subtitle": "तपाईंको समुदाय स्थान। कथाहरू साझा गर्नुहोस्, जितहरू मनाउनुहोस्, र सुनरे गाउनसँग जोडिइ रहनुहोस्।",
        "hub.join": "समुदायमा सामेल हुनुहोस्",
        "hub.explore": "स्थानहरू अन्वेषण गर्नुहोस्",
        "hub.explore.desc": "गाउँको आफ्नो कुना खोज्नुहोस्",
        "hub.enter": "अन्वेषण गर्नुहोस्",
        "hub.creators": "सिर्जकहरूको कुना",
        "hub.creators.desc": "गाउँको जीवन देखाउने भिडियो निर्माता, टिकटकर्स र सामग्री सिर्जकहरू",
        "hub.youth": "युवा आवाजहरू",
        "hub.youth.desc": "बालबालिकाको कला, विद्यालयका उपलब्धिहरू र सुनरेका भविष्यका प्रतिभाहरू",
        "hub.mothers": "आमाको सर्कल",
        "hub.mothers.desc": "पुस्तौं पुस्तासम्म सारिएका परिकार, परम्पराहरू र ज्ञान",
        "hub.fathers": "बुवाको गिल्ड",
        "hub.fathers.desc": "गाउँ निर्माताहरूबाट निर्माण, खेती सुझावहरू र मार्गदर्शन",
        "hub.updates": "विकास नोटहरू",
        "hub.updates.desc": "गाउँ घोषणाहरू, योजनाहरू र सामुदायिक बैठकहरू",
        "hub.praises": "प्रशंसा र गौरव",
        "hub.praises.desc": "उपलब्धिहरू, धन्यवाद नोटहरू र चाड हाइलाइटहरू",
        "hub.stats.members": "सदस्यहरू",
        "hub.stats.families": "परिवारहरू",
        "hub.stats.stories": "कथाहरू",

        // Personality Test
        "hub.personality": "मेरो व्यक्तित्व खोज्नुहोस्",
        "hub.personality.desc": "हाम्रो गाउँ-शैली क्विजमार्फत आफ्नो साँचो स्वरूप पत्ता लगाउनुहोस्!",
        "personality.title": "गाउँ व्यक्तित्व क्विज",
        "personality.subtitle": "१० प्रश्न। निर्मम इमानदार परिणामहरू।",
        "personality.start": "क्विज सुरु गर्नुहोस्",
        "personality.submit": "मेरो साँचो स्वरूप खोल्नुहोस्",
        "personality.retake": "फेरि क्विज लिनुहोस्",

        // Village Page
        "village.title": "गाउँ",
        "village.talent": "प्रतिभा",
        "village.subtitle": "लामाहट्टालाई विशेष बनाउने सिर्जक, गाइड र कारीगरहरू पत्ता लगाउनुहोस्।",
        "village.noPortfolios": "अहिले सम्म कुनै पोर्टफोलियो छैन। पहिलो बन्नुहोस्!",
        "village.createPortfolio": "आफ्नो पोर्टफोलियो बनाउनुहोस्",

        // Common
        "common.loading": "लोड हुँदैछ...",
        "common.partnerWithUs": "हामीसँग साझेदारी गर्नुहोस्",

        // Investor Section
        "investor.label": "लगानीकर्ताहरूको लागि",
        "investor.title": "तपाईंलाई एउटा पत्र",
        "investor.greeting": "प्रिय लगानीकर्ता,",
        "investor.p1": "यदि तपाईं दार्जीलिङको पहाडमा भ्रमण घर, होमस्टे, रेस्टुरेन्ट, वा रिट्रीट बनाउन जमिन खोज्दै हुनुहुन्छ भने — सुनरे गाउनमा स्वागत छ।",
        "investor.p2": "हाम्रो गाउँ लामाहट्टाको छेउमा छ, पाइन जंगल र पहाडको दृश्यले घेरिएको छ। हामीसँग २२ घरहरू, ९३ बासिन्दाहरू, र छिटो पैसाभन्दा होसियार बृद्धिलाई महत्त्व दिने समुदाय छ।",
        "investor.p3": "हाम्रो जमिनलाई सम्मान गर्ने, हाम्रा मानिसहरूलाई संलग्न गराउने, र स्थानीय अर्थतन्त्रमा योगदान गर्ने साझेदारीमा हामी खुला छौं।",
        "investor.closing": "हामी सानो हुँदा हामीसँग उभिनेहरूलाई सम्झन्छौं।",
        "investor.formTitle": "लगानीमा रुचि छ?",
        "investor.phone": "फोन नम्बर",
        "investor.interest": "तपाईं के मा रुचि राख्नुहुन्छ?",
        "investor.submit": "सम्पर्क गर्नुहोस्",
        "investor.success": "धन्यवाद! हामी चाँडै सम्पर्कमा हुनेछौं।",

        // Partners
        "partners.label": "लगानी र सहयोग",
        "partners.title": "हामीसँग काम गर्नुहोस्",
        "partners.subtitle": "हामी साँच्चै सेवा गर्छौं, होसियारसँग बढ्छौं, र सम्झन्छौं।",
        "partners.experience": "यहाँ आउने मानिसहरूले अनुभव गर्छन्:",
        "partners.quote": "हामी तमाशा बेच्दैनौं। हामी विश्वास बनाउँछौं।",
        "partners.formTitle": "साझेदारीमा रुचि छ?",
        "partners.formDesc": "लगानी अवसरहरू, सहयोग, वा भ्रमणको लागि सम्पर्क गर्नुहोस्।",
        "partners.submit": "सम्पर्क गर्नुहोस्",
        "partners.success": "धन्यवाद! हामी चाँडै जवाफ दिनेछौं।",
    },

    HI: {
        "nav.home": "होम",
        "nav.why": "यह क्यों मौजूद है",
        "nav.change": "बदलाव",
        "nav.economy": "हम क्या करते हैं",
        "nav.challenges": "चुनौतियाँ",
        "nav.voices": "आवाज़ें",
        "nav.partners": "भागीदार",
        "nav.updates": "अपडेट",
        "hero.location": "लामाहट्टा · दार्जीलिंग",
        "hero.title": "सुनरे गाउन",
        "hero.subtitle": "संक्रमण में एक गाँव की अर्थव्यवस्था",
        "hero.houses": "घर",
        "hero.residents": "निवासी",
        "hero.potential": "संभावना",
        "hero.scroll": "नीचे स्क्रॉल करें ↓",
        "hero.opportunity": "अवसर देखें",
        "hero.story": "हमारी कहानी",
        "opportunities.title": "अवसर",
        "opportunities.villagers": "ग्रामीणों के लिए",
        "opportunities.villagers.desc": "सेवाएं, योजनाएं और अवसर प्राप्त करें",
        "opportunities.investors": "निवेशकों के लिए",
        "opportunities.investors.desc": "अवसर की खाई देखें",
        "opportunities.partners": "भागीदारों के लिए",
        "opportunities.partners.desc": "हमारे साथ सहयोग करें",
        "opportunities.enter": "प्रवेश →",
        "location.label": "स्थान",
        "location.title": "हम कहाँ हैं",
        "location.subtitle": "6वें माइल और ताकदाह के बीच। पहाड़ों में छिपा हुआ रत्न।",
        "location.satellite": "उपग्रह दृश्य",
        "location.houses": "जंगल में बसे 22 घर",
        "location.maps": "Google Maps में खोलें ↗",
        "life.quote": "अच्छा खाना। ईमानदार मेहमाननवाज़ी। हास्य और गर्मजोशी। अपनापन।",
        "life.attribution": "— आगंतुक यहाँ क्या अनुभव करते हैं",
        "gaps.label": "निवेशकों के लिए",
        "gaps.title": "अवसर की खाई",
        "gaps.subtitle": "उच्च मांग। शून्य आपूर्ति। निवेश के लिए आदर्श।",
        "gaps.homestay": "होमस्टे",
        "gaps.cafe": "कैफे",
        "gaps.guide": "गाइड",
        "gaps.organic": "जैविक खेती",
        "gaps.status": "खाई",
        "gaps.potential": "होमस्टे क्षमता: पहाड़ी दृश्य, प्रामाणिक अनुभव",
        "economy.label": "सक्रिय अर्थव्यवस्था",
        "economy.title": "हम क्या करते हैं",
        "economy.subtitle": "खाना बनाने से कोडिंग तक। एक कामकाजी गाँव अर्थव्यवस्था।",
        "economy.view": "सभी सेवाएं देखें",
        "economy.food": "खाना और मेहमाननवाज़ी",
        "economy.agriculture": "कृषि",
        "economy.construction": "निर्माण",
        "economy.digital": "डिजिटल सेवाएं",
        "economy.active": "सक्रिय",
        "vision.label": "दृष्टि",
        "vision.title": "हम क्या बना रहे हैं",
        "vision.portal": "गाँव पोर्टल",
        "vision.portal.desc": "सभी सेवाओं के लिए एक प्लेटफॉर्म",
        "vision.hub": "पर्यटन हब",
        "vision.hub.desc": "पहाड़ियों के बीच गंतव्य",
        "vision.network": "कौशल नेटवर्क",
        "vision.network.desc": "प्रतिभा अवसर से मिलती है",
        "vision.quote": "हम पहुँच का इंतज़ार नहीं कर रहे। हम पहले अर्थव्यवस्था बना रहे हैं।",
        "cta.title": "कहानी का हिस्सा बनने के लिए तैयार?",
        "cta.partner": "हमारे साथ भागीदारी करें",
        "cta.story": "हमारी कहानी पढ़ें",
        "footer.tagline": "लामाहट्टा, दार्जीलिंग के एक छोटे गाँव का जीवित रिकॉर्ड। 22 घर। ~93 लोग। एक कहानी।",
        "footer.navigate": "नेविगेट",
        "footer.connected": "जुड़े रहें",
        "footer.connected.desc": "स्थानीय अपडेट, सरकारी योजनाएं, अवसर।",
        "footer.subscribe": "अपडेट के लिए सदस्यता लें →",
        "footer.credit": "जीवित रिकॉर्ड · सुनरे गाउन, लामाहट्टा, दार्जीलिंग",
        "footer.unfinished": "यह साइट पूरी नहीं हुई है। न ही गाँव।",

        // Sunlight Hub
        "hub.title": "सनलाइट हब",
        "hub.subtitle": "आपका सामुदायिक स्थान। कहानियाँ साझा करें, जीत का जश्न मनाएं, और सुनरे गाउन से जुड़े रहें।",
        "hub.join": "समुदाय में शामिल हों",
        "hub.explore": "स्थानों का अन्वेषण करें",
        "hub.explore.desc": "गाँव में अपना कोना खोजें",
        "hub.enter": "अन्वेषण करें",
        "hub.creators": "क्रिएटर्स कॉर्नर",
        "hub.creators.desc": "गाँव की जिंदगी दिखाने वाले वीडियो मेकर्स, टिकटॉकर्स और कंटेंट क्रिएटर्स",
        "hub.youth": "युवा आवाजें",
        "hub.youth.desc": "बच्चों की कला, स्कूल की उपलब्धियाँ और सुनरे की भविष्य की प्रतिभाएं",
        "hub.mothers": "माँ का सर्कल",
        "hub.mothers.desc": "पीढ़ियों से चली आ रही रेसिपी, परंपराएं और ज्ञान",
        "hub.fathers": "पिता का गिल्ड",
        "hub.fathers.desc": "गाँव के निर्माताओं से निर्माण, खेती की सलाह और मार्गदर्शन",
        "hub.updates": "विकास नोट्स",
        "hub.updates.desc": "गाँव की घोषणाएं, योजनाएं और सामुदायिक बैठकें",
        "hub.praises": "प्रशंसा और गौरव",
        "hub.praises.desc": "उपलब्धियाँ, धन्यवाद नोट्स और त्योहार हाइलाइट्स",
        "hub.stats.members": "सदस्य",
        "hub.stats.families": "परिवार",
        "hub.stats.stories": "कहानियाँ",

        // Personality Test
        "hub.personality": "मेरा व्यक्तित्व खोजें",
        "hub.personality.desc": "हमारी गाँव-शैली क्विज से अपना असली स्वरूप जानें!",
        "personality.title": "गाँव व्यक्तित्व क्विज",
        "personality.subtitle": "10 सवाल। बेरहमी से ईमानदार परिणाम।",
        "personality.start": "क्विज शुरू करें",
        "personality.submit": "मेरा असली स्वरूप दिखाएं",
        "personality.retake": "क्विज फिर से लें",

        // Village Page
        "village.title": "गाँव",
        "village.talent": "प्रतिभा",
        "village.subtitle": "उन रचनाकारों, गाइडों और कारीगरों की खोज करें जो लामाहट्टा को खास बनाते हैं।",
        "village.noPortfolios": "अभी तक कोई पोर्टफोलियो नहीं। पहले बनें!",
        "village.createPortfolio": "अपना पोर्टफोलियो बनाएं",

        // Common
        "common.loading": "लोड हो रहा है...",
        "common.partnerWithUs": "हमारे साथ भागीदारी करें",

        // Investor Section
        "investor.label": "निवेशकों के लिए",
        "investor.title": "आपके लिए एक पत्र",
        "investor.greeting": "प्रिय निवेशक,",
        "investor.p1": "यदि आप दार्जीलिंग की पहाड़ियों में छुट्टियों का घर, होमस्टे, रेस्तरां, या रिट्रीट बनाने के लिए जमीन ढूंढ रहे हैं — सुनरे गाउन में आपका स्वागत है।",
        "investor.p2": "हमारा गाँव लामाहट्टा के किनारे पर है, पाइन के जंगलों और पहाड़ी दृश्यों से घिरा हुआ। हमारे पास 22 घर, 93 निवासी, और एक समुदाय है जो तेज पैसे से ज्यादा सावधानीपूर्ण विकास को महत्व देता है।",
        "investor.p3": "हम उन साझेदारियों के लिए खुले हैं जो हमारी जमीन का सम्मान करती हैं, हमारे लोगों को शामिल करती हैं, और स्थानीय अर्थव्यवस्था में योगदान देती हैं।",
        "investor.closing": "हम उन्हें याद रखते हैं जो हमारे छोटे होने पर हमारे साथ खड़े थे।",
        "investor.formTitle": "निवेश में रुचि है?",
        "investor.phone": "फोन नंबर",
        "investor.interest": "आप किसमें रुचि रखते हैं?",
        "investor.submit": "संपर्क करें",
        "investor.success": "धन्यवाद! हम जल्द ही संपर्क करेंगे।",

        // Partners
        "partners.label": "निवेश और सहयोग",
        "partners.title": "हमारे साथ काम करें",
        "partners.subtitle": "हम सच्ची सेवा करते हैं, सावधानी से बढ़ते हैं, और याद रखते हैं।",
        "partners.experience": "यहाँ आने वाले लोग अनुभव करते हैं:",
        "partners.quote": "हम तमाशा नहीं बेचते। हम विश्वास बनाते हैं।",
        "partners.formTitle": "साझेदारी में रुचि है?",
        "partners.formDesc": "निवेश अवसरों, सहयोग, या यात्राओं के लिए संपर्क करें।",
        "partners.submit": "संपर्क करें",
        "partners.success": "धन्यवाद! हम जल्द जवाब देंगे।",
    },

    BN: {
        "nav.home": "হোম",
        "nav.why": "এটি কেন বিদ্যমান",
        "nav.change": "পরিবর্তন",
        "nav.economy": "আমরা কী করি",
        "nav.challenges": "চ্যালেঞ্জ",
        "nav.voices": "কণ্ঠস্বর",
        "nav.partners": "অংশীদার",
        "nav.updates": "আপডেট",
        "hero.location": "লামাহাট্টা · দার্জিলিং",
        "hero.title": "সুনরে গাউন",
        "hero.subtitle": "রূপান্তরে একটি গ্রাম অর্থনীতি",
        "hero.houses": "বাড়ি",
        "hero.residents": "বাসিন্দা",
        "hero.potential": "সম্ভাবনা",
        "hero.scroll": "নিচে স্ক্রোল করুন ↓",
        "hero.opportunity": "সুযোগ দেখুন",
        "hero.story": "আমাদের গল্প",
        "opportunities.title": "সুযোগ",
        "opportunities.villagers": "গ্রামবাসীদের জন্য",
        "opportunities.villagers.desc": "পরিষেবা, স্কিম এবং সুযোগ অ্যাক্সেস করুন",
        "opportunities.investors": "বিনিয়োগকারীদের জন্য",
        "opportunities.investors.desc": "সুযোগের ফাঁক দেখুন",
        "opportunities.partners": "অংশীদারদের জন্য",
        "opportunities.partners.desc": "আমাদের সাথে সহযোগিতা করুন",
        "opportunities.enter": "প্রবেশ করুন →",
        "location.label": "অবস্থান",
        "location.title": "আমরা কোথায় আছি",
        "location.subtitle": "৬ষ্ঠ মাইল এবং তাকদাহের মধ্যে। পাহাড়ে লুকানো রত্ন।",
        "location.satellite": "স্যাটেলাইট ভিউ",
        "location.houses": "বনের মধ্যে ২২টি বাড়ি",
        "location.maps": "Google Maps এ খুলুন ↗",
        "life.quote": "ভালো খাবার। সৎ আতিথেয়তা। হাস্যরস এবং উষ্ণতা। আপনত্বের অনুভূতি।",
        "life.attribution": "— দর্শনার্থীরা এখানে যা অনুভব করেন",
        "gaps.label": "বিনিয়োগকারীদের জন্য",
        "gaps.title": "সুযোগের ফাঁক",
        "gaps.subtitle": "উচ্চ চাহিদা। শূন্য সরবরাহ। বিনিয়োগের জন্য আদর্শ।",
        "gaps.homestay": "হোমস্টে",
        "gaps.cafe": "ক্যাফে",
        "gaps.guide": "গাইড",
        "gaps.organic": "জৈব চাষ",
        "gaps.status": "ফাঁক",
        "gaps.potential": "হোমস্টে সম্ভাবনা: পাহাড়ের দৃশ্য, প্রামাণিক অভিজ্ঞতা",
        "economy.label": "সক্রিয় অর্থনীতি",
        "economy.title": "আমরা কী করি",
        "economy.subtitle": "রান্না থেকে কোডিং পর্যন্ত। একটি কর্মক্ষম গ্রাম অর্থনীতি।",
        "economy.view": "সব পরিষেবা দেখুন",
        "economy.food": "খাবার ও আতিথেয়তা",
        "economy.agriculture": "কৃষি",
        "economy.construction": "নির্মাণ",
        "economy.digital": "ডিজিটাল পরিষেবা",
        "economy.active": "সক্রিয়",
        "vision.label": "দৃষ্টি",
        "vision.title": "আমরা কী বানাচ্ছি",
        "vision.portal": "গ্রাম পোর্টাল",
        "vision.portal.desc": "সব পরিষেবার জন্য এক প্ল্যাটফর্ম",
        "vision.hub": "পর্যটন হাব",
        "vision.hub.desc": "পাহাড়ের মধ্যে গন্তব্য",
        "vision.network": "দক্ষতা নেটওয়ার্ক",
        "vision.network.desc": "প্রতিভা সুযোগের সাথে মিলিত হয়",
        "vision.quote": "আমরা অ্যাক্সেসের জন্য অপেক্ষা করছি না। আমরা প্রথমে অর্থনীতি তৈরি করছি।",
        "cta.title": "গল্পের অংশ হতে প্রস্তুত?",
        "cta.partner": "আমাদের সাথে অংশীদার হন",
        "cta.story": "আমাদের গল্প পড়ুন",
        "footer.tagline": "লামাহাট্টা, দার্জিলিংয়ের একটি ছোট গ্রামের জীবন্ত রেকর্ড। ২২টি বাড়ি। ~৯৩ জন। একটি গল্প।",
        "footer.navigate": "নেভিগেট",
        "footer.connected": "সংযুক্ত থাকুন",
        "footer.connected.desc": "স্থানীয় আপডেট, সরকারি স্কিম, সুযোগ।",
        "footer.subscribe": "আপডেটের জন্য সাবস্ক্রাইব করুন →",
        "footer.credit": "জীবন্ত রেকর্ড · সুনরে গাউন, লামাহাট্টা, দার্জিলিং",
        "footer.unfinished": "এই সাইট শেষ হয়নি। গ্রামও না।",

        // Sunlight Hub
        "hub.title": "সানলাইট হাব",
        "hub.subtitle": "আপনার কমিউনিটি স্পেস। গল্প শেয়ার করুন, জয় উদযাপন করুন, এবং সুনরে গাউনের সাথে সংযুক্ত থাকুন।",
        "hub.join": "কমিউনিটিতে যোগ দিন",
        "hub.explore": "স্থানগুলো অন্বেষণ করুন",
        "hub.explore.desc": "গ্রামে আপনার কোণ খুঁজুন",
        "hub.enter": "অন্বেষণ করুন",
        "hub.creators": "ক্রিয়েটর্স কর্নার",
        "hub.creators.desc": "গ্রামের জীবন দেখানো ভিডিও মেকার, টিকটকার এবং কনটেন্ট ক্রিয়েটর",
        "hub.youth": "তরুণ কণ্ঠ",
        "hub.youth.desc": "শিশুদের শিল্প, স্কুলের অর্জন এবং সুনরের ভবিষ্যত প্রতিভা",
        "hub.mothers": "মায়ের সার্কেল",
        "hub.mothers.desc": "প্রজন্ম থেকে প্রজন্মে চলে আসা রেসিপি, ঐতিহ্য এবং জ্ঞান",
        "hub.fathers": "বাবার গিল্ড",
        "hub.fathers.desc": "গ্রামের নির্মাতাদের কাছ থেকে নির্মাণ, চাষের টিপস এবং পরামর্শ",
        "hub.updates": "উন্নয়ন নোট",
        "hub.updates.desc": "গ্রামের ঘোষণা, স্কিম এবং কমিউনিটি মিটিং",
        "hub.praises": "প্রশংসা ও গর্ব",
        "hub.praises.desc": "অর্জন, ধন্যবাদ নোট এবং উৎসবের হাইলাইট",
        "hub.stats.members": "সদস্য",
        "hub.stats.families": "পরিবার",
        "hub.stats.stories": "গল্প",

        // Personality Test
        "hub.personality": "আমার ব্যক্তিত্ব খুঁজুন",
        "hub.personality.desc": "আমাদের গ্রাম-স্টাইল কুইজ দিয়ে আপনার প্রকৃত স্বরূপ আবিষ্কার করুন!",
        "personality.title": "গ্রাম ব্যক্তিত্ব কুইজ",
        "personality.subtitle": "১০টি প্রশ্ন। নির্মম সৎ ফলাফল।",
        "personality.start": "কুইজ শুরু করুন",
        "personality.submit": "আমার প্রকৃত স্বরূপ দেখান",
        "personality.retake": "আবার কুইজ নিন",

        // Village Page
        "village.title": "গ্রাম",
        "village.talent": "প্রতিভা",
        "village.subtitle": "লামাহাট্টাকে বিশেষ করে তোলা সৃষ্টিকর্তা, গাইড এবং কারিগরদের আবিষ্কার করুন।",
        "village.noPortfolios": "এখনও কোনো পোর্টফোলিও নেই। প্রথম হন!",
        "village.createPortfolio": "আপনার পোর্টফোলিও তৈরি করুন",

        // Common
        "common.loading": "লোড হচ্ছে...",
        "common.partnerWithUs": "আমাদের সাথে অংশীদার হন",

        // Investor Section
        "investor.label": "বিনিয়োগকারীদের জন্য",
        "investor.title": "আপনার জন্য একটি চিঠি",
        "investor.greeting": "প্রিয় বিনিয়োগকারী,",
        "investor.p1": "আপনি যদি দার্জিলিংয়ের পাহাড়ে ছুটির বাড়ি, হোমস্টে, রেস্তোরাঁ বা রিট্রিট তৈরি করতে জমি খুঁজছেন — সুনরে গাউনে স্বাগতম।",
        "investor.p2": "আমাদের গ্রাম লামাহাট্টার প্রান্তে, পাইন বন এবং পাহাড়ি দৃশ্য দ্বারা বেষ্টিত। আমাদের ২২টি বাড়ি, ৯৩ জন বাসিন্দা এবং দ্রুত টাকার চেয়ে সতর্ক বৃদ্ধিকে মূল্য দেওয়া একটি সম্প্রদায় আছে।",
        "investor.p3": "আমাদের জমিকে সম্মান করে, আমাদের মানুষদের জড়িত করে এবং স্থানীয় অর্থনীতিতে অবদান রাখে এমন অংশীদারিত্বে আমরা উন্মুক্ত।",
        "investor.closing": "আমরা মনে রাখি কারা আমাদের ছোট থাকতে পাশে দাঁড়িয়েছিল।",
        "investor.formTitle": "বিনিয়োগে আগ্রহী?",
        "investor.phone": "ফোন নম্বর",
        "investor.interest": "আপনি কিসে আগ্রহী?",
        "investor.submit": "যোগাযোগ করুন",
        "investor.success": "ধন্যবাদ! আমরা শীঘ্রই যোগাযোগ করব।",

        // Partners
        "partners.label": "বিনিয়োগ ও সহযোগিতা",
        "partners.title": "আমাদের সাথে কাজ করুন",
        "partners.subtitle": "আমরা সত্যিকারের সেবা করি, সতর্কভাবে বাড়ি এবং মনে রাখি।",
        "partners.experience": "এখানে আসা মানুষরা অভিজ্ঞতা করেন:",
        "partners.quote": "আমরা দর্শনীয়তা বিক্রি করি না। আমরা বিশ্বাস তৈরি করি।",
        "partners.formTitle": "অংশীদারিত্বে আগ্রহী?",
        "partners.formDesc": "বিনিয়োগ সুযোগ, সহযোগিতা বা পরিদর্শনের জন্য যোগাযোগ করুন।",
        "partners.submit": "যোগাযোগ করুন",
        "partners.success": "ধন্যবাদ! আমরা শীঘ্রই উত্তর দেব।",
    },

    DZ: {
        // Bhutanese/Dzongkha
        "nav.home": "མདུན་ཤོག",
        "nav.why": "འདི་ག་ཅི་སྦེ་ཡོདཔ",
        "nav.change": "བསྒྱུར་བཅོས",
        "nav.economy": "ང་བཅས་ག་ཅི་འབདཝ",
        "nav.challenges": "དཀའ་ངལ",
        "nav.voices": "སྐད་སྒྲ",
        "nav.partners": "མཉམ་འབྲེལ",
        "nav.updates": "གསར་བཏོན",
        "hero.location": "ལ་མ་ཧཊྭཱ · དར་ཇི་གླིང",
        "hero.title": "Seemana Gaon",
        "hero.subtitle": "གྱུར་བའི་གཡུས་ཚན་དཔལ་འབྱོར",
        "hero.houses": "ཁྱིམ",
        "hero.residents": "མི་སེར",
        "hero.potential": "ནུས་པ",
        "hero.scroll": "མར་བཤུད ↓",
        "hero.opportunity": "གོ་སྐབས་བལྟ",
        "hero.story": "ང་བཅས་ཀྱི་ལོ་རྒྱུས",
        "opportunities.title": "གོ་སྐབས",
        "opportunities.villagers": "གཡུས་མིའི་དོན་ལུ",
        "opportunities.villagers.desc": "ཞབས་ཏོག་དང་གོ་སྐབས་ལེན",
        "opportunities.investors": "མ་རྩ་བཙུགས་མི་དོན་ལུ",
        "opportunities.investors.desc": "གོ་སྐབས་ཀྱི་སྟོངམ་བལྟ",
        "opportunities.partners": "མཉམ་འབྲེལ་པའི་དོན་ལུ",
        "opportunities.partners.desc": "ང་བཅས་དང་མཉམ་འབྲེལ་འབད",
        "opportunities.enter": "ནང་འཛུལ →",
        "location.label": "ས་གནས",
        "location.title": "ང་བཅས་ག་ཏེ་ཡོད",
        "location.subtitle": "མའི་ལི་དྲུག་པ་དང་ཏཀ་དྷ་བར་ན། རི་ནང་གི་རིན་ཐང་ཅན།",
        "location.satellite": "མཁའ་དབྱིངས་མཐོང་ཚད",
        "location.houses": "ནགས་ནང་གི་ཁྱིམ་ཉི་ཤུ་རྩ་གཉིས",
        "location.maps": "Google Maps ནང་ཁ་ཕྱེ ↗",
        "life.quote": "བཟའ་ནོར་ལེགས། བསྟུན་འགྲིགས་བདེནམ། གད་མོ་དང་དྲོ་བ། རང་ཁྱིམ་འདྲ།",
        "life.attribution": "— འགྱོ་མི་གིས་ནཱ་མྱོང་བ",
        "vision.quote": "ང་བཅས་འབྱོར་ལམ་བསྒུགས་མིན་འདུག། ང་བཅས་ཧེ་མ་དཔལ་འབྱོར་བཟོ་དོ།",
        "cta.title": "ལོ་རྒྱུས་ཀྱི་ཆ་ཤས་འགྱོ་ནིའི་གྲ་སྒྲིག་ཡོད?",
        "cta.partner": "ང་བཅས་དང་མཉམ་འབྲེལ་འབད",
        "cta.story": "ང་བཅས་ཀྱི་ལོ་རྒྱུས་ལྷག",
    },

    TB: {
        // Tibetan
        "nav.home": "མདུན་ཤོག",
        "nav.why": "འདི་ག་རེ་ཡིན",
        "nav.change": "འགྱུར་བ",
        "nav.economy": "ང་ཚོ་གང་བྱེད",
        "nav.challenges": "དཀའ་ངལ",
        "nav.voices": "སྐད་སྒྲ",
        "nav.partners": "མཉམ་འབྲེལ་བ",
        "nav.updates": "གསར་གཏོད",
        "hero.location": "ལ་མ་ཧཊྭཱ · དར་རྒྱས་གླིང",
        "hero.title": "Seemana Gaon",
        "hero.subtitle": "འགྱུར་བཞིན་པའི་གྲོང་གསེབ་དཔལ་འབྱོར",
        "hero.houses": "ཁང་པ",
        "hero.residents": "མི་སེར",
        "hero.potential": "ནུས་པ",
        "hero.scroll": "མར་འཁྱེར ↓",
        "hero.opportunity": "གོ་སྐབས་ལྟ",
        "hero.story": "ང་ཚོའི་ལོ་རྒྱུས",
        "opportunities.title": "གོ་སྐབས",
        "opportunities.villagers": "གྲོང་མིའི་ཆེད",
        "opportunities.villagers.desc": "ཞབས་ཞུ་དང་གོ་སྐབས་ལེན",
        "opportunities.investors": "མ་རྩ་འཇོག་མཁན་ཆེད",
        "opportunities.investors.desc": "གོ་སྐབས་བར་སྟོང་ལྟ",
        "opportunities.partners": "མཉམ་ལས་པའི་ཆེད",
        "opportunities.partners.desc": "ང་ཚོ་དང་མཉམ་ལས་བྱོས",
        "opportunities.enter": "འཛུལ →",
        "location.label": "ས་གནས",
        "location.title": "ང་ཚོ་གང་དུ་ཡོད",
        "location.subtitle": "དྲུག་པ་མའིལ་དང་ཏཀ་དྷ་བར། རི་ཁྲོད་ཀྱི་རིན་ཐང་ཆེན།",
        "vision.quote": "ང་ཚོ་ལྷན་ལམ་སྒུག་གི་མིན། ང་ཚོ་སྔོན་ལ་དཔལ་འབྱོར་བཟོ་གི་ཡོད།",
        "cta.title": "ལོ་རྒྱུས་ཀྱི་ཆ་ཤས་བྱེད་འདོད་ཡོད་དམ?",
        "cta.partner": "ང་ཚོ་དང་མཉམ་འབྲེལ་བྱོས",
        "cta.story": "ང་ཚོའི་ལོ་རྒྱུས་ཀློག",
    },

    SH: {
        // Sherpa
        "nav.home": "Tse-khang",
        "nav.why": "Di garé yin",
        "nav.change": "Gyur-wa",
        "nav.economy": "Nga-tsö ka jé",
        "nav.challenges": "Kang-ngal",
        "nav.voices": "Ké-dra",
        "nav.partners": "Nyam-drel-wa",
        "nav.updates": "Sar-tön",
        "hero.location": "Lama-hatta · Darjeeling",
        "hero.title": "Seemana Gaon",
        "hero.subtitle": "Gyur-zhin-pé Yul-chung Pal-jor",
        "hero.houses": "Khangpa",
        "hero.residents": "Mi-ser",
        "hero.potential": "Nü-pa",
        "hero.scroll": "Marla teng ↓",
        "hero.opportunity": "Go-kab ta",
        "hero.story": "Nga-tsö Lo-gyü",
        "opportunities.title": "Go-kab",
        "opportunities.villagers": "Yul-mi ché",
        "opportunities.villagers.desc": "Zhab-zhü dang go-kab len",
        "opportunities.investors": "Ma-tsa jog-khen ché",
        "opportunities.investors.desc": "Go-kab bar-tong ta",
        "opportunities.partners": "Nyam-lé-pa ché",
        "opportunities.partners.desc": "Nga-tsö dang nyam-lé jö",
        "opportunities.enter": "Dzü →",
        "location.label": "Sa-né",
        "location.title": "Nga-tsö gang-du yö",
        "location.subtitle": "6th Mile dang Takdah bar. Ri-khé rin-thang chen.",
        "vision.quote": "Nga-tsö thon-lam gü-gi min. Nga-tsö ngön-la pal-jor zo-gi yö.",
        "cta.title": "Lo-gyü cha-shé jé-dö yö-pe?",
        "cta.partner": "Nga-tsö dang nyam-drel jö",
        "cta.story": "Nga-tsö lo-gyü log",
    },

    ZH: {
        // Chinese
        "nav.home": "首页",
        "nav.why": "为什么存在",
        "nav.change": "变化",
        "nav.economy": "我们做什么",
        "nav.challenges": "挑战",
        "nav.voices": "声音",
        "nav.partners": "合作伙伴",
        "nav.updates": "更新",
        "hero.location": "拉马哈塔 · 大吉岭",
        "hero.title": "Seemana Gaon",
        "hero.subtitle": "转型中的乡村经济",
        "hero.houses": "房屋",
        "hero.residents": "居民",
        "hero.potential": "潜力",
        "hero.scroll": "向下滚动 ↓",
        "hero.opportunity": "查看机会",
        "hero.story": "我们的故事",
        "opportunities.title": "机会",
        "opportunities.villagers": "村民专区",
        "opportunities.villagers.desc": "获取服务、计划和机会",
        "opportunities.investors": "投资者专区",
        "opportunities.investors.desc": "查看机会缺口",
        "opportunities.partners": "合作伙伴专区",
        "opportunities.partners.desc": "与我们合作",
        "opportunities.enter": "进入 →",
        "location.label": "位置",
        "location.title": "我们在哪里",
        "location.subtitle": "位于6英里和塔克达之间。山间隐藏的宝石。",
        "location.satellite": "卫星视图",
        "location.houses": "森林中的22栋房屋",
        "location.maps": "在Google Maps中打开 ↗",
        "life.quote": "美食。诚挚的热情款待。幽默与温暖。归属感。",
        "life.attribution": "— 游客在这里的体验",
        "gaps.label": "投资者专区",
        "gaps.title": "机会缺口",
        "gaps.subtitle": "高需求。零供应。投资的理想选择。",
        "gaps.homestay": "民宿",
        "gaps.cafe": "咖啡馆",
        "gaps.guide": "导游",
        "gaps.organic": "有机农场",
        "gaps.status": "缺口",
        "gaps.potential": "民宿潜力：山景，真实体验",
        "economy.label": "活跃经济",
        "economy.title": "我们做什么",
        "economy.subtitle": "从烹饪到编程。一个运转中的乡村经济。",
        "economy.view": "查看所有服务",
        "economy.food": "餐饮与款待",
        "economy.agriculture": "农业",
        "economy.construction": "建筑",
        "economy.digital": "数字服务",
        "economy.active": "活跃",
        "vision.label": "愿景",
        "vision.title": "我们正在建设什么",
        "vision.portal": "村庄门户",
        "vision.portal.desc": "所有服务的统一平台",
        "vision.hub": "旅游中心",
        "vision.hub.desc": "山间的目的地",
        "vision.network": "技能网络",
        "vision.network.desc": "人才遇见机会",
        "vision.quote": "我们不等待接入。我们先建设经济。",
        "cta.title": "准备好成为故事的一部分了吗？",
        "cta.partner": "与我们合作",
        "cta.story": "阅读我们的故事",
        "footer.tagline": "大吉岭拉马哈塔一个小村庄的生活记录。22栋房屋。约93人。一个故事。",
        "footer.navigate": "导航",
        "footer.connected": "保持联系",
        "footer.connected.desc": "本地更新、政府计划、机会。",
        "footer.subscribe": "订阅更新 →",
        "footer.credit": "生活记录 · Seemana Gaon, 拉马哈塔, 大吉岭",
        "footer.unfinished": "这个网站尚未完成。村庄也是。",
    },

    TH: {
        // Thai
        "nav.home": "หน้าแรก",
        "nav.why": "ทำไมถึงมีอยู่",
        "nav.change": "การเปลี่ยนแปลง",
        "nav.economy": "เราทำอะไร",
        "nav.challenges": "ความท้าทาย",
        "nav.voices": "เสียง",
        "nav.partners": "พันธมิตร",
        "nav.updates": "อัปเดต",
        "hero.location": "ลามาฮัตตา · ดาร์จีลิ่ง",
        "hero.title": "Seemana Gaon",
        "hero.subtitle": "เศรษฐกิจหมู่บ้านที่กำลังเปลี่ยนแปลง",
        "hero.houses": "บ้าน",
        "hero.residents": "ผู้อยู่อาศัย",
        "hero.potential": "ศักยภาพ",
        "hero.scroll": "เลื่อนลง ↓",
        "hero.opportunity": "ดูโอกาส",
        "hero.story": "เรื่องราวของเรา",
        "opportunities.title": "โอกาส",
        "opportunities.villagers": "สำหรับชาวบ้าน",
        "opportunities.villagers.desc": "เข้าถึงบริการ โครงการ และโอกาส",
        "opportunities.investors": "สำหรับนักลงทุน",
        "opportunities.investors.desc": "ดูช่องว่างโอกาส",
        "opportunities.partners": "สำหรับพันธมิตร",
        "opportunities.partners.desc": "ร่วมมือกับเรา",
        "opportunities.enter": "เข้าสู่ →",
        "location.label": "ที่ตั้ง",
        "location.title": "เราอยู่ที่ไหน",
        "location.subtitle": "ระหว่างไมล์ที่ 6 และทักดาห์ อัญมณีที่ซ่อนอยู่ในภูเขา",
        "location.satellite": "มุมมองดาวเทียม",
        "location.houses": "22 หลังคาเรือนในป่า",
        "location.maps": "เปิดใน Google Maps ↗",
        "life.quote": "อาหารอร่อย การต้อนรับที่จริงใจ อารมณ์ขันและความอบอุ่น ความรู้สึกเป็นส่วนหนึ่ง",
        "life.attribution": "— สิ่งที่ผู้มาเยือนสัมผัสได้ที่นี่",
        "vision.quote": "เราไม่รอการเข้าถึง เราสร้างเศรษฐกิจก่อน",
        "cta.title": "พร้อมที่จะเป็นส่วนหนึ่งของเรื่องราวแล้วหรือยัง?",
        "cta.partner": "ร่วมเป็นพันธมิตรกับเรา",
        "cta.story": "อ่านเรื่องราวของเรา",
        "footer.tagline": "บันทึกชีวิตของหมู่บ้านเล็กๆ ในลามาฮัตตา ดาร์จีลิ่ง 22 บ้าน ~93 คน หนึ่งเรื่องราว",
        "footer.navigate": "นำทาง",
        "footer.connected": "เชื่อมต่อ",
        "footer.connected.desc": "อัปเดตท้องถิ่น โครงการรัฐบาล โอกาส",
        "footer.subscribe": "สมัครรับการอัปเดต →",
        "footer.credit": "บันทึกชีวิต · Seemana Gaon, Lamahatta, Darjeeling",
        "footer.unfinished": "เว็บไซต์นี้ยังไม่เสร็จ หมู่บ้านก็เช่นกัน",
    },

    FR: {
        // French
        "nav.home": "Accueil",
        "nav.why": "Pourquoi ça existe",
        "nav.change": "Changement",
        "nav.economy": "Ce que nous faisons",
        "nav.challenges": "Défis",
        "nav.voices": "Voix",
        "nav.partners": "Partenaires",
        "nav.updates": "Mises à jour",
        "hero.location": "Lamahatta · Darjeeling",
        "hero.title": "Seemana Gaon",
        "hero.subtitle": "Une économie villageoise en transition",
        "hero.houses": "Maisons",
        "hero.residents": "Résidents",
        "hero.potential": "Potentiel",
        "hero.scroll": "Défiler pour explorer ↓",
        "hero.opportunity": "Voir l'opportunité",
        "hero.story": "Notre histoire",
        "opportunities.title": "Opportunités",
        "opportunities.villagers": "Pour les villageois",
        "opportunities.villagers.desc": "Accédez aux services, programmes et opportunités",
        "opportunities.investors": "Pour les investisseurs",
        "opportunities.investors.desc": "Voir les opportunités manquantes",
        "opportunities.partners": "Pour les partenaires",
        "opportunities.partners.desc": "Collaborez avec nous",
        "opportunities.enter": "Entrer →",
        "location.label": "Emplacement",
        "location.title": "Où nous sommes",
        "location.subtitle": "Entre 6th Mile et Takdah. Un joyau caché dans les collines.",
        "location.satellite": "Vue satellite",
        "location.houses": "22 maisons nichées dans la forêt",
        "location.maps": "Ouvrir dans Google Maps ↗",
        "life.quote": "Bonne nourriture. Hospitalité honnête. Humour et chaleur. Un sentiment d'appartenance.",
        "life.attribution": "— Ce que les visiteurs vivent ici",
        "gaps.label": "Pour les investisseurs",
        "gaps.title": "Opportunités manquantes",
        "gaps.subtitle": "Forte demande. Aucune offre. Idéal pour l'investissement.",
        "gaps.homestay": "Hébergement",
        "gaps.cafe": "Café",
        "gaps.guide": "Guide",
        "gaps.organic": "Ferme bio",
        "gaps.status": "Manque",
        "gaps.potential": "Potentiel d'hébergement: Vue montagne, expérience authentique",
        "economy.label": "Économie active",
        "economy.title": "Ce que nous faisons",
        "economy.subtitle": "De la cuisine au codage. Une économie villageoise fonctionnelle.",
        "economy.view": "Voir tous les services",
        "economy.food": "Alimentation & Hospitalité",
        "economy.agriculture": "Agriculture",
        "economy.construction": "Construction",
        "economy.digital": "Services numériques",
        "economy.active": "actif",
        "vision.label": "La vision",
        "vision.title": "Ce que nous construisons",
        "vision.portal": "Portail du village",
        "vision.portal.desc": "Une plateforme pour tous les services",
        "vision.hub": "Hub touristique",
        "vision.hub.desc": "Destination entre les collines",
        "vision.network": "Réseau de compétences",
        "vision.network.desc": "Le talent rencontre l'opportunité",
        "vision.quote": "Nous n'attendons pas l'accès. Nous construisons d'abord une économie.",
        "cta.title": "Prêt à faire partie de l'histoire ?",
        "cta.partner": "Devenez partenaire",
        "cta.story": "Lire notre histoire",
        "footer.tagline": "Un document vivant d'un petit village à Lamahatta, Darjeeling. 22 maisons. ~93 personnes. Une histoire.",
        "footer.navigate": "Naviguer",
        "footer.connected": "Rester connecté",
        "footer.connected.desc": "Actualités locales, programmes gouvernementaux, opportunités.",
        "footer.subscribe": "S'abonner aux mises à jour →",
        "footer.credit": "Document vivant · Seemana Gaon, Lamahatta, Darjeeling",
        "footer.unfinished": "Ce site n'est pas fini. Le village non plus.",
    },
};

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
    const [language, setLanguage] = useState<Language>("EN");

    const t = (key: string): string => {
        return translations[language]?.[key] || translations["EN"]?.[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};
